import type { Planner, Venue, BlogPost, ArticleBlock, RealWedding, EditorialMember, UseCase, Lead } from './types';

export const PLANNERS: Planner[] = [
  {
    verified: false, id: 'sara', name: 'Sara Llabrés', firm: 'Slow Finca',
    location: 'Pollença', style: 'Finca · slow',
    types: ['finca', 'intimate'],
    guests: '20–60', minGuests: 20, maxGuests: 60,
    minBudget: 25000, maxBudget: 60000,
    season: 'Spring · autumn', price: '£8,000–14,000',
    rating: '4.96', reviews: 54, scene: 'finca',
    img: '/img/couple-hills.webp', featured: true,
    tagline: 'Small, slow weddings in the Tramuntana foothills',
    signatureLine: 'I take eight weddings a year. No more. Every couple gets my mobile number.',
    bio: "I grew up on a finca outside Pollença, ran weddings as someone else's planner for six years, then opened Slow Finca to do exactly the eight weddings a year I wanted to do — and no more. I work with couples who like a long lunch, who want the day to feel like it was always supposed to happen here, who don't want to be the project manager of their own wedding. The stone walls and citrus trees do most of the heavy lifting. My job is to keep the rest of the day quiet, on schedule, and honest to the place.",
    languages: ['English', 'Castellano', 'Català'],
    based: 'Pollença, Mallorca', response: '95% within 8h',
    avgResponse: '6 hours', weddingsPerYear: '8 weddings / year',
    instagram: '@slow.finca', nextAvailable: 'Booking 2027 from May',
    deposit: '€2,500 to confirm a date',
    badges: ['Verified', 'Guest favourite'],
    photos: ['/img/couple-hills.webp', '/img/wedding-detail.webp', '/img/couple-bouquet.webp', '/img/couple-portrait.webp', '/img/couple-veil.webp'],
    specialisms: [
      { ico: 'flame',  t: 'Small, slow days',    s: '20–60 guests · single venue · long lunch into the evening.' },
      { ico: 'home',   t: 'Tramuntana fincas',   s: '12 years of relationships with the families behind the venues.' },
      { ico: 'leaf',   t: 'In-season food',      s: 'I bring local growers and chefs you cannot find on TripAdvisor.' },
      { ico: 'shield', t: 'UK couples',          s: 'I know how UK families plan, what your registrars need, where the plug sockets are wrong.' },
    ],
    services: [
      { tier: 'Full planning', price: 'From £8,500', popular: true,
        bullets: ['12-month lead time', 'Venue search if needed', 'Full supplier curation', 'On-the-day coordination', 'Paperwork & translation', 'Up to 60 guests'] },
      { tier: 'Day-of coordination', price: 'From £2,400',
        bullets: ['Final 6–8 weeks', 'Supplier handover from you', 'Run-sheet + timeline', 'On-the-day coordination (12h)', "You've done the planning; I bring it home"] },
      { tier: 'Venue access (estate only)', price: 'From £6,500/day',
        bullets: ['Estate hire for 40 max', 'Kitchen + accommodation for 12', 'Tables, chairs, basic AV', 'No catering or planning included'] },
    ],
    process: [
      { n: '01', t: 'Free discovery call', s: "30 minutes on Zoom. I ask about you, the day you're picturing, what scares you about planning from abroad." },
      { n: '02', t: 'Proposal & contract', s: 'Within 5 days. Fixed-fee, no commissions. Deposit confirms your date.' },
      { n: '03', t: 'Design & sourcing (months 1–6)', s: 'Venue, suppliers, design board, paperwork timeline. Monthly call, weekly WhatsApp.' },
      { n: '04', t: 'Final 8 weeks', s: 'Run-sheet, supplier confirmations, walkthroughs. Daily contact in the final 2 weeks.' },
      { n: '05', t: 'On the day', s: "I arrive at 7am. I leave when the last guest does. You get to be a guest at your own wedding." },
    ],
    reviewsData: [
      { name: 'Kate & James', date: 'May 2025', guests: 38, venue: 'Finca Comassema',
        body: "Quietly competent. Sara made the day feel like an afternoon at a friend's house — which is exactly what we asked for. The Friday welcome dinner in Pollença old town was her idea and was, honestly, our favourite part." },
      { name: 'Daisy & Tom', date: 'Sep 2024', guests: 52, venue: 'Son Marroig',
        body: "We were planning from London and had no idea where to start. Three months in we already trusted Sara more than ourselves. The day itself was effortless because of months of small decisions she had already made for us." },
      { name: 'Ruth & Mark', date: 'Jun 2024', guests: 44, venue: 'Slow Finca (estate)',
        body: "Five days of 'this is handled' in a row. Sara has the rare skill of making you feel like you're her only couple. Would recommend to anyone planning from outside Spain." },
      { name: 'Hollie & Tom', date: 'May 2024', guests: 56, venue: 'Finca Comassema',
        body: "Sara talked us out of two things we would have regretted and into one thing (a string quartet for the ceremony) we now cannot imagine the day without. She runs a small operation and that is the entire point." },
    ],
    faqs: [
      { q: 'Do I need to come to Mallorca during planning?', a: "Most couples come twice — once to see venues (months 1–2), once for a final walkthrough (final 4 weeks). I can do all venue tours myself with video if you can't." },
      { q: 'How do you charge — flat fee or percentage?', a: 'Flat fee. Always. I don\'t take commissions from suppliers. If a supplier offers, I deduct the equivalent from your invoice instead.' },
      { q: "What's the smallest wedding you'll plan?", a: '20 guests. Anything smaller is an elopement and I\'d point you to a colleague who specialises.' },
      { q: 'Can you handle multi-day weekends?', a: 'Yes — welcome dinners, Sunday paellas, the works. About a third of my couples do a full weekend.' },
      { q: 'Will you be there on the day?', a: 'Yes, always. I don\'t pass weddings to assistants. If something stops me, I have one trusted colleague who has worked every wedding with me for three years.' },
    ],
    preferredVenues: ['son-marroig', 'finca-comassema', 'son-togores'], yearsActive: 9,
  },
  {
    verified: false, id: 'laura', name: 'Laura · Titila', firm: 'TITILA Eventos Integrales',
    location: 'Mallorca', style: 'Destination · multi-cultural',
    types: ['luxury', 'multi-day', 'indian', 'finca', 'intimate'],
    guests: '20–300', minGuests: 20, maxGuests: 300,
    minBudget: 25000, maxBudget: 300000,
    season: 'Year-round', price: 'POA',
    rating: '5.0', reviews: 15, scene: 'tramuntana',
    img: '/img/couple-dancing.webp', featured: false,
    tagline: 'Destination weddings across Spain — Mallorca, Seville, Ibiza and beyond.',
    signatureLine: 'Planning a wedding from another country felt effortless. The result? Warm, elegant, completely magical.',
    bio: "TITILA is a full-service destination wedding planning studio led by Laura, covering Mallorca, Seville, Ibiza, Barcelona and across Spain. With a background in luxury event production, Laura specialises in complex, multi-cultural and destination celebrations — weddings that involve international guest lists, multiple cultural ceremonies, and multi-day programmes. She is fluent in English, Spanish and French, handles all local vendor negotiations directly, and is known for the calm she brings to ambitious plans.",
    languages: ['English', 'Castellano', 'French'],
    based: 'Mallorca & Seville', response: '90% within 24h',
    avgResponse: '12 hours', weddingsPerYear: '15+ weddings / year',
    instagram: '@titila.es', nextAvailable: 'Enquire for availability',
    deposit: 'Deposit on confirmation',
    badges: ['Verified'],
    photos: ['/img/couple-dancing.webp', '/img/couple-portrait.webp', '/img/wedding-detail.webp', '/img/comassema-9.webp', '/img/comassema-3.webp'],
    specialisms: [
      { ico: 'sparkles', t: 'Multi-cultural weddings', s: 'Hindu, Chinese, Spanish and international ceremonies. Laura has planned them all with the same care.' },
      { ico: 'sun',      t: 'Multi-day programmes',    s: 'Welcome dinners, ceremony days, day-after events — the full destination wedding weekend.' },
      { ico: 'guests',   t: 'Large scale',              s: 'From 20 guests to 300. Laura has planned complex 200-guest destination weddings from scratch.' },
      { ico: 'globe',    t: 'International couples',    s: 'Most clients plan from the UK, US or further afield. English, Spanish and French spoken fluently.' },
    ],
    services: [
      { tier: 'Turnkey planning', price: 'POA', popular: true,
        bullets: ['Complete planning from concept to execution', 'Venue and vendor sourcing', 'Custom production design', 'Guest experience planning', 'On-site coordination', 'Recommended: 10+ months lead time'] },
      { tier: 'Day-of coordination', price: 'POA',
        bullets: ['Month-of support for self-planned weddings', 'Supplier briefings and handover', 'Full on-the-day management', 'Recommended: 4–6 months lead time'] },
    ],
    process: [
      { n: '01', t: 'Free discovery call', s: 'Laura meets you on Zoom. She listens, asks questions, and tells you honestly whether she\'s the right fit.' },
      { n: '02', t: 'Creative proposal', s: 'A personalised concept document covering venue options, design direction and a realistic budget breakdown.' },
      { n: '03', t: 'Vendor negotiations', s: 'Laura sources and negotiates with every supplier directly in Spanish, saving time and typically money.' },
      { n: '04', t: 'Your day', s: 'Laura and her team are on-site from setup to close. Your guests feel the calm; you feel nothing but joy.' },
    ],
    reviewsData: [
      { name: 'Candelle Chong', date: '2024', guests: 250, venue: 'Salamanca', stars: 5,
        body: "Thank you to Laura and the Titila team. Our wedding was over 2 days — a Chinese tea ceremony followed by a full Spanish civil wedding with 250 guests from across the world. A complex wedding which Laura executed perfectly.", source: 'google' },
      { name: 'Sona Raich', date: '2024', guests: 200, venue: 'Destination', stars: 5,
        body: "We planned our Hindu destination wedding for 200 people with Laura & Titila last year, and we can truly say it was the best week of our lives. Laura has an incredible eye for beauty and everything ran seamlessly.", source: 'google' },
      { name: 'Kristy Churchman', date: '2024', guests: 0, venue: 'Spain', stars: 5,
        body: "I absolutely loved working with Laura – she made the entire wedding planning experience so much easier and genuinely fun! She was super supportive from start to finish and has fantastic taste.", source: 'google' },
      { name: 'Anthony Tang', date: '2024', guests: 0, venue: 'Seville', stars: 5,
        body: "10/10 would recommend. We're from London and Laura was brilliant at communication, organisation and keeping us calm. On the day she really stood out — it went perfectly.", source: 'google' },
    ],
    faqs: [
      { q: 'Do you only work in Mallorca?', a: 'No — TITILA plans weddings across Spain including Mallorca, Ibiza, Seville, Barcelona, Marbella and more. Laura can advise on which destination suits your vision best.' },
      { q: 'Do you plan multi-cultural weddings?', a: 'Yes — this is one of our specialities. Laura has planned Hindu, Chinese, Spanish and mixed-culture celebrations, often with multiple ceremonies over several days.' },
      { q: 'How do you work with international couples?', a: 'Most of our couples plan from the UK, US or further afield. All planning is done remotely until the venue visit. Laura is fluent in English, Spanish and French.' },
      { q: 'What is the minimum budget you work with?', a: 'We work with celebrations from €25,000 upwards. Most Mallorca destination weddings we plan fall in the €60,000–€150,000+ range.' },
    ],
    preferredVenues: ['finca-comassema', 'finca-son-berga', 'finca-son-mir'], yearsActive: 10,
  },
  {
    verified: false, id: 'charlotte', name: 'Charlotte von Proschwitz', firm: 'Mallorca Wedding Planners',
    location: 'Palma', style: 'Full-service · luxury',
    types: ['luxury', 'multi-day', 'finca', 'beach', 'intimate'],
    guests: '20–200', minGuests: 20, maxGuests: 200,
    minBudget: 30000, maxBudget: 250000,
    season: 'Year-round', price: 'POA',
    rating: '4.3', reviews: 26, scene: 'sea',
    img: '/img/couple-veil.webp', featured: true,
    tagline: 'Full-service wedding production in Mallorca for 15 years.',
    signatureLine: 'We turn your vision into reality — from the first venue visit to the last dance.',
    bio: "Charlotte von Proschwitz has been planning and producing weddings in Mallorca for 15 years. With a background in international journalism and events experience in New York, she brings structure, creativity and cultural fluency to every celebration. Charlotte works with couples from across Europe and North America, managing everything from venue sourcing and floral design to lighting production, entertainment, catering and day-of coordination. Her team speaks English, Swedish, French and Spanish.",
    languages: ['English', 'Swedish', 'French', 'Castellano'],
    based: 'Palma, Mallorca', response: '90% within 24h',
    avgResponse: '12 hours', weddingsPerYear: '20+ weddings / year',
    instagram: '@mallorcaweddingplanners', nextAvailable: 'Enquire for availability',
    deposit: 'Deposit on confirmation',
    badges: ['Verified'],
    photos: ['/img/couple-veil.webp', '/img/couple-bouquet.webp', '/img/wedding-detail.webp', '/img/son-marroig-9.webp', '/img/son-marroig-7.webp'],
    specialisms: [
      { ico: 'gem',      t: 'Luxury production',      s: 'Full event production — lighting, florals, furniture, entertainment, all in-house.' },
      { ico: 'sun',      t: 'Multi-day celebrations',  s: 'Yacht days, welcome parties, ceremonies, pool parties — Charlotte coordinates the whole weekend.' },
      { ico: 'globe',    t: 'International couples',   s: 'English, Swedish, French and Spanish. Most clients are flying in from the US, UK or Scandinavia.' },
      { ico: 'home',     t: '15 years on the island',  s: 'Deep vendor relationships across every type of venue — fincas, hotels, beaches and private estates.' },
    ],
    services: [
      { tier: 'Full planning & production', price: 'POA', popular: true,
        bullets: ['Venue sourcing and selection', 'Floral design and styling', 'Lighting and decoration', 'Entertainment and musicians', 'Photography and videography', 'Hair, makeup and catering'] },
      { tier: 'Day-of coordination', price: 'POA',
        bullets: ['Final weeks handover', 'Supplier briefings', 'Full on-the-day management', 'For couples who\'ve done their own planning'] },
    ],
    process: [
      { n: '01', t: 'Free discovery call', s: 'We discuss your vision, budget and key requirements. Charlotte personally reviews every enquiry.' },
      { n: '02', t: 'Venue visit', s: 'Charlotte takes you through shortlisted venues. Most couples decide within the first day of viewings.' },
      { n: '03', t: 'Planning phase', s: 'Full supplier sourcing, design development and logistics. Charlotte negotiates directly in Spanish with all local vendors.' },
      { n: '04', t: 'Your day', s: 'Charlotte and her team are on-site from setup to close. You focus on your guests; they handle everything else.' },
    ],
    reviewsData: [
      { name: 'Sharon Seckman', date: '2024', guests: 0, venue: 'Mallorca', stars: 5,
        body: "Hiring Charlotte from Mallorca Wedding Planners was the best decision we made for our daughter\'s wedding. Charlotte and her team exceeded every expectation we had.", source: 'google' },
      { name: 'Dara Kirke', date: '2024', guests: 0, venue: 'Mallorca', stars: 5,
        body: "Cannot give Charlotte and her team enough praise! Charlotte came highly recommended to us by a close friend whose wedding she had planned. And I am so grateful — it was the most magical day.", source: 'google' },
      { name: 'Jessica Roach', date: '2024', guests: 0, venue: 'Mallorca', stars: 5,
        body: "Charlotte helped us plan a four day wedding celebration in Mallorca that included a yacht day, welcome party, wedding, and pool party. She is extremely kind and incredibly professional.", source: 'google' },
      { name: 'James Lowry', date: '2024', guests: 0, venue: 'Mallorca', stars: 5,
        body: "Where do we start! Everything we could have imagined and more. Our wedding — quote \'wedding of the year\' by our guests. Everything was perfect, we didn\'t have to worry about a thing.", source: 'google' },
      { name: 'Natalie Nelson', date: '2023', guests: 0, venue: 'Castillo de Bendinat', stars: 5,
        body: "We had the wedding of our dreams at Castillo de Bendinat and it was all because of Charlotte and her amazing team! From beginning to end, Charlotte was there every step of the way.", source: 'google' },
      { name: 'Annabel Welch', date: '2023', guests: 0, venue: 'Mallorca', stars: 5,
        body: "Everything from start to finish was absolutely incredible. Charlotte spent a lot of time with us while looking at venues and really listened to the vibe that we were going for.", source: 'google' },
      { name: 'Samantha Best', date: '2019', guests: 0, venue: 'Finca Son Mir', stars: 5,
        body: "We had the most wonderful and memorable day of our lives at Finca Son Mir... all because Charlotte and the team captured every detail from start to finish.", source: 'google' },
      { name: 'Monica Rodriguez', date: '2024', guests: 0, venue: 'Mallorca', stars: 5,
        body: "We are so grateful to Charlotte and Selena for creating the most amazing and wonderful wedding for us. My husband, my family, and I cannot thank them enough.", source: 'google' },
    ],
    faqs: [
      { q: 'Do you handle the whole wedding or just coordination?', a: 'We do both — full planning and production from day one, or day-of coordination for couples who have done their own planning. Most clients choose full service.' },
      { q: 'Do you work with international couples?', a: 'Yes — most of our couples are from the US, UK, Sweden and France. Charlotte speaks all four languages and handles all local vendor negotiations in Spanish.' },
      { q: 'Can you organise a multi-day celebration?', a: 'Yes. Yacht days, welcome dinners, ceremonies and pool parties are all things we regularly coordinate. The multi-day wedding is our most popular format.' },
      { q: 'What areas of Mallorca do you cover?', a: 'All of Mallorca — from Palma and the southwest coast to the Tramuntana mountains and the north. We have venue relationships across the whole island.' },
    ],
    preferredVenues: ['son-marroig', 'finca-son-mir', 'finca-comassema'],
    yearsActive: 15,
  },
  {
    verified: false, id: 'katja', name: 'Katja Redweik', firm: 'Mallorca Boutique Weddings',
    location: 'Palma', style: 'Boutique · design-led',
    types: ['luxury', 'intimate', 'multi-day', 'finca', 'villa'],
    guests: '20–150', minGuests: 20, maxGuests: 150,
    minBudget: 25000, maxBudget: 200000,
    season: 'Year-round', price: 'POA',
    rating: '4.7', reviews: 13, scene: 'bougainvil',
    img: '/img/couple-portrait.webp', featured: false,
    tagline: 'Thoughtfully designed weddings. No language barriers, no stress.',
    signatureLine: 'By entrusting us with your wedding planning, you save time, money — and the stress of planning abroad.',
    bio: "Katja Redweik grew up in Frankfurt, lived in Berlin, Barcelona and London, and has been based in Palma de Mallorca since 2007. With a background in economics, marketing and over 20 years in event and television production — including her own production company in Barcelona — she brings a creative director's eye to wedding planning. She founded Mallorca Boutique Weddings to give international couples a truly personalised service: thoughtful design, careful management, and a celebration that feels elegant and personal rather than packaged.",
    languages: ['English', 'Deutsch', 'Castellano'],
    based: 'Palma, Mallorca', response: '90% within 24h',
    avgResponse: '12 hours', weddingsPerYear: '15+ weddings / year',
    instagram: '@mallorca_boutique_weddings', nextAvailable: 'Enquire for availability',
    deposit: 'Deposit on confirmation',
    badges: ['Verified'],
    photos: ['/img/couple-portrait.webp', '/img/couple-bouquet.webp', '/img/couple-dancing.webp', '/img/togores-3.webp', '/img/togores-6.webp'],
    specialisms: [
      { ico: 'sparkle',  t: 'Boutique design',        s: 'Original, contemporary style brought to every wedding. Not a template in sight.' },
      { ico: 'globe',    t: 'International couples',   s: 'English, German and Spanish. Most clients are planning from the UK, US or Germany.' },
      { ico: 'gem',      t: '20+ years of production', s: 'Television and event production background means every detail is managed professionally.' },
      { ico: 'leaf',     t: 'Trusted local suppliers', s: 'Over a decade of supplier relationships in Mallorca. She negotiates in Spanish on your behalf.' },
    ],
    services: [
      { tier: 'Full planning & design', price: 'POA', popular: true,
        bullets: ['Personalised venue sourcing', 'Supplier management', 'Styling and décor design', 'Logistics planning', 'On-the-day coordination', 'Wedding concierge platform'] },
      { tier: 'Partial planning', price: 'POA',
        bullets: ['Venue already chosen', 'Supplier curation from that point', 'Design input', 'On-the-day management'] },
    ],
    process: [
      { n: '01', t: 'Discovery meeting', s: 'Katja meets you in person or on video. She listens first — your vision, your priorities, what matters most.' },
      { n: '02', t: 'Design concept', s: 'A personalised design concept is developed — not a package, not a template.' },
      { n: '03', t: 'Vendor sourcing', s: 'Using established relationships built over 15+ years, Katja sources and negotiates with every supplier.' },
      { n: '04', t: 'Your day', s: 'Katja and her team manage everything on the day. You focus on your guests and enjoy every moment.' },
    ],
    reviewsData: [
      { name: 'alexandra supel', date: '2024', guests: 0, venue: 'Mallorca', stars: 5,
        body: "I HIGHLY recommend Katja and Mallorca Boutique Weddings! We knew we wanted to have a destination wedding in Mallorca, but the thought of planning from New York felt overwhelming. Katja made everything seamless.", source: 'google' },
      { name: 'Rob Indietobe', date: '2024', guests: 0, venue: 'Mallorca', stars: 5,
        body: "Katja is absolutely amazing! Everything was beautifully organised, personal, and stress-free from start to finish. She truly cares about every detail and makes the whole wedding experience feel magical.", source: 'google' },
      { name: 'andreas poulakidas', date: '2024', guests: 0, venue: 'Mallorca', stars: 5,
        body: "Katja is simply the best! Everything went super smoothly and all guests were amazed by our party. We did not have to take care of anything except choosing the most important things.", source: 'google' },
      { name: 'Agnieszka Supel', date: '2024', guests: 0, venue: 'Finca Son Berga', stars: 5,
        body: "Katja was the wedding planner for my daughter's wedding at Finca Son Berga. Our journey began almost a year and a half before the wedding. Katja guided us through every step with professionalism and warmth.", source: 'google' },
      { name: 'Tabitha Smith', date: '2023', guests: 0, venue: 'Private villa', stars: 5,
        body: "Katja and her team organised our wedding in July 2023. She found a fantastic villa for the venue and the 3-day events were all truly magical.", source: 'google' },
      { name: 'thomas kasteel', date: '2025', guests: 0, venue: 'Mallorca', stars: 5,
        body: "I was a guest at a wedding they planned and honestly… everything just worked. No stress, no chaos, everything flowed really well. The vibe was amazing.", source: 'google' },
      { name: 'Roger Castellví', date: '2025', guests: 0, venue: 'Mallorca', stars: 5,
        body: "It has always been a pleasure working with Katja and her team. Having known her for more than a decade, I can confidently say that her weddings are consistently beautiful and well-executed.", source: 'google' },
      { name: 'Nils Schubert', date: '2024', guests: 0, venue: 'Mallorca', stars: 5,
        body: "Das war der beste Service, die höchste Qualität und die schönste Hochzeit die ich mir wünschen konnte. Einfach Großartig.", source: 'google' },
    ],
    faqs: [
      { q: 'Do you work with couples planning from abroad?', a: 'Yes — most of our couples are planning from the UK, US or Germany. Katja speaks English, German and Spanish and handles everything locally on your behalf.' },
      { q: 'What makes Mallorca Boutique Weddings different?', a: 'A truly personalised service — no packages, no templates. Katja brings her background in television production to create something original for every couple.' },
      { q: 'What areas of Mallorca do you cover?', a: 'All of Mallorca, plus Ibiza and Formentera. Katja has supplier relationships across the whole island built over 15+ years.' },
      { q: 'Do you handle multi-day celebrations?', a: 'Yes. Villa weekends, welcome dinners, ceremonies and day-after events are all things Katja regularly coordinates.' },
    ],
    preferredVenues: ['finca-son-mir', 'son-togores', 'finca-son-berga'], yearsActive: 18,
  },
  {
    verified: false, id: 'marcos', name: 'Marcos Rama', firm: 'Pure Weddings Mallorca',
    location: 'Palma', style: 'Luxury · bespoke',
    types: ['luxury', 'finca', 'beach', 'multi-day', 'villa'],
    guests: '20–200', minGuests: 20, maxGuests: 200,
    minBudget: 30000, maxBudget: 250000,
    season: 'Year-round', price: 'POA',
    rating: '5.0', reviews: 37, scene: 'olive',
    img: '/img/wedding-detail.webp', featured: false,
    tagline: 'Bespoke weddings at exclusive Mallorca locations. 5.0 stars. 37 reviews.',
    signatureLine: 'My perfectionist eye for detail and 10 years directing events at luxury hotels — now entirely yours.',
    bio: "Marcos Rama was born in Switzerland to Spanish parents, studied International Hotel Management in Palma, and fell in love with Mallorca. After spending 10 years as Director of Events at prestigious luxury hotels across the island, he founded Pure Weddings Mallorca to bring that level of precision and hospitality to destination weddings. Marcos works alongside Manu, and together they're known for their attention to detail, constant communication, and an ability to make couples from North America, the UK and Europe feel completely at ease planning from abroad.",
    languages: ['English', 'Castellano', 'Deutsch', 'French'],
    based: 'Palma, Mallorca', response: '95% within 12h',
    avgResponse: '8 hours', weddingsPerYear: '20+ weddings / year',
    instagram: '@pureweddingsmallorca', nextAvailable: 'Enquire for availability',
    deposit: 'Deposit on confirmation',
    badges: ['Verified'],
    photos: ['/img/wedding-detail.webp', '/img/couple-hills.webp', '/img/couple-dancing.webp', '/img/comassema-7.webp', '/img/comassema-5.webp'],
    specialisms: [
      { ico: 'gem',     t: 'Luxury hotel expertise',   s: '10 years as Events Director at top Mallorca hotels. That standard now applied to weddings.' },
      { ico: 'globe',   t: 'International couples',    s: 'Marcos and Manu work with couples from North America, the UK, Switzerland and across Europe.' },
      { ico: 'sparkle', t: 'Bespoke design',           s: 'Every wedding reflects the couple\'s true essence — never a template, never a package.' },
      { ico: 'guests',  t: 'Stress-free planning',     s: 'Constant communication, clear timelines, honest advice. Couples consistently say planning felt fun.' },
    ],
    services: [
      { tier: 'Full planning', price: 'POA', popular: true,
        bullets: ['Complete planning from concept to day', 'Venue selection at exclusive locations', 'Full vendor sourcing and management', 'Marcos and Manu on-site all day', 'Constant communication throughout'] },
      { tier: 'Day-of coordination', price: 'POA',
        bullets: ['For couples who\'ve done their own planning', 'Final weeks supplier briefings', 'Full on-the-day management by Marcos and Manu'] },
    ],
    process: [
      { n: '01', t: 'Discovery call', s: 'Marcos listens to your vision, your priorities, and what kind of day you want. No pressure, no pitch.' },
      { n: '02', t: 'Venue selection', s: 'Using his extensive network, Marcos identifies exclusive venues that match your vision and budget.' },
      { n: '03', t: 'Vendor curation', s: 'Drawing on relationships built over 10+ years in Mallorca\'s luxury hotel industry, every supplier is selected with care.' },
      { n: '04', t: 'Your wedding day', s: 'Marcos and Manu are there from setup to close. Couples consistently say they were able to fully relax and enjoy the day.' },
    ],
    reviewsData: [
      { name: 'Pascalle Vallen', date: '2024', guests: 0, venue: 'Mallorca', stars: 5,
        body: "We had the absolute pleasure of working with Pure Weddings Mallorca for our three-day wedding celebration, and Marcos and Manu delivered beyond all expectations. Every single detail was flawlessly executed.", source: 'google' },
      { name: 'Ashton Williams', date: '2025', guests: 0, venue: 'Mallorca', stars: 5,
        body: "Truly had the most wonderful experience working with Manu & Marcos. As a destination bride coming from North America I was so nervous about planning on another continent. They made it feel completely natural.", source: 'google' },
      { name: 'Eleanor Kirkham', date: '2024', guests: 0, venue: 'Mallorca', stars: 5,
        body: "The entire experience was beyond our wildest dreams and it was all down to Marcos. We have very busy schedules in London so knew we needed a planner in Mallorca we could trust completely.", source: 'google' },
      { name: 'Christie Bok', date: '2024', guests: 0, venue: 'Mallorca', stars: 5,
        body: "Marcos and his team are an absolute dream to work with! From the moment we started planning, Marcos' extensive knowledge of every vendor in Mallorca was evident.", source: 'google' },
      { name: 'Yasmeen Amid', date: '2025', guests: 0, venue: 'Mallorca', stars: 5,
        body: "Marcos and Manu were absolutely INCREDIBLE wedding coordinators. They were timely, took care of every detail, and made sure our vision was brought to life in the most magical way.", source: 'google' },
      { name: 'Nina Obreshkova', date: '2025', guests: 0, venue: 'Mallorca', stars: 5,
        body: "Planning our wedding with Pure Weddings Mallorca was the best decision we made — and that is entirely down to Marcos and Manu!", source: 'google' },
      { name: 'Marco Roduner', date: '2024', guests: 0, venue: 'Mallorca', stars: 5,
        body: "Wir haben im Juni auf Mallorca geheiratet und danken Marcos von Herzen für seine grossartige Unterstützung! In der Vorbereitung war er jederzeit erreichbar und hat unsere Wünsche perfekt umgesetzt.", source: 'google' },
      { name: 'Lucie J', date: '2024', guests: 0, venue: 'Mallorca', stars: 5,
        body: "Manu and Marcos are the definition of excellence. Every detail was thoughtfully planned and executed, communication was clear — especially important when planning a wedding from abroad.", source: 'google' },
    ],
    faqs: [
      { q: 'What makes Pure Weddings Mallorca different?', a: "Marcos spent 10 years as Events Director at luxury hotels in Mallorca. That level of professional precision — combined with genuine warmth — is what couples consistently describe." },
      { q: 'Do you work with couples planning from abroad?', a: 'Yes — most of our couples are from the UK, North America, Switzerland and across Europe. Marcos speaks English, Spanish, German and French.' },
      { q: 'Do you handle multi-day celebrations?', a: 'Yes. Three-day weekends, welcome dinners, yacht days — Marcos and Manu regularly coordinate complex multi-day celebrations.' },
      { q: 'What venues do you work with?', a: 'Exclusive venues across Mallorca and the Balearics. Marcos has built relationships over years at the top end of the island\'s event industry.' },
    ],
    preferredVenues: ['son-marroig', 'son-togores', 'finca-comassema'], yearsActive: 10,
  },
  {
    verified: false, id: 'elena', name: 'Elena Mateu', firm: 'Citrus & Salt',
    location: 'Valldemossa', style: 'Florist & styling',
    types: ['florist', 'intimate'],
    guests: '10–200', minGuests: 10, maxGuests: 200,
    minBudget: 8000, maxBudget: 25000,
    season: 'Year-round', price: '£1,200–4,500',
    rating: '4.99', reviews: 62, scene: 'citrus',
    img: '/img/couple-bouquet.webp', featured: true,
    tagline: 'Seasonal flowers from the Mallorcan hills',
    signatureLine: 'I source from local growers in the Tramuntana. Everything close to the land.',
    bio: "I source from local growers in the Tramuntana and Plà — olive branches, citrus blossom, soft-coloured roses, herbs from the hillsides. I keep everything close to the land and the season. I'm not a wedding planner; I'm the person who makes the space feel like it was meant to look this way.",
    languages: ['English', 'Castellano'],
    based: 'Valldemossa, Mallorca', response: '98% within 4h',
    avgResponse: '3 hours', weddingsPerYear: '30+ weddings / year',
    instagram: '@citrusandsalt', nextAvailable: 'Booking 2026 & 2027',
    deposit: '€800 to confirm a date',
    badges: ['Verified', 'Guest favourite'],
    photos: ['/img/couple-bouquet.webp', '/img/wedding-detail.webp', '/img/couple-veil.webp', '/img/togores-5.webp', '/img/son-marroig-8.webp'],
    specialisms: [
      { ico: 'florist', t: 'Seasonal florals',    s: 'Only in-season, only from growers I know by name.' },
      { ico: 'leaf',    t: 'Mallorcan botanicals', s: 'Olive, citrus, rosemary, almond. The island on a table.' },
      { ico: 'sparkles','t': 'Full styling',        s: 'Florals, lighting, signage, paper goods — the complete picture.' },
      { ico: 'camera',  t: 'Photo-first design',   s: 'I\'ve worked with enough photographers to know what photographs beautifully.' },
    ],
    services: [
      { tier: 'Wedding florals', price: 'From £1,400', popular: true,
        bullets: ['Bridal bouquet', 'Ceremony florals', 'Long-table installation', 'Buttonholes & accessories', 'Seasonal, locally sourced'] },
      { tier: 'Full styling', price: 'From £3,200',
        bullets: ['Tablescapes & centrepieces', 'Candles & lighting', 'Signage & paper goods', 'Ceremony arch or installation', 'Florals included'] },
    ],
    reviewsData: [
      { name: 'Sarah & Tom', date: 'Jun 2025', guests: 80, venue: 'Son Marroig',
        body: "Elena's flowers were the first thing every guest mentioned. She used olive branches and citrus from somewhere near Valldemossa and it looked like the land had dressed the table itself." },
      { name: 'Kate & Alex', date: 'Jun 2025', guests: 60, venue: 'Son Togores',
        body: "We gave Elena one reference image and a colour palette. Everything else was her. The result was more beautiful than anything we\'d have chosen ourselves." },
    ],
    faqs: [
      { q: 'Do you work with any wedding planner?', a: 'Yes — I work alongside any planner or directly with couples who are self-planning.' },
      { q: 'Can I request specific flowers?', a: 'Always, within season. If something isn\'t in season I\'ll tell you honestly and suggest what\'s better.' },
    ],
    preferredVenues: ['son-marroig', 'son-togores', 'finca-comassema'], yearsActive: 6,
  },
  {
    verified: true, id: 'awhitehotwedding',
    name: 'Olivia Skeen & Lucy',
    firm: 'A White Hot Wedding',
    location: 'Port Adriano',
    style: 'Full-service · styling',
    types: ['finca', 'luxury', 'intimate', 'indian', 'multi-day'],
    guests: '10–250',
    minGuests: 10, maxGuests: 250,
    minBudget: 20000, maxBudget: 200000,
    season: 'Year-round',
    price: 'POA',
    rating: '4.8', reviews: 26,
    scene: 'bougainvil',
    img: '/img/couple-portrait.webp',
    featured: true,
    tagline: '20 years on the island. Two planners, one wedding. Double the help.',
    signatureLine: 'Two of us means one always has eyes on the room — and on you.',
    bio: "Olivia and Lucy are a planning partnership based full-time in Port Adriano. Between them they have 20 years of Mallorca wedding knowledge — every finca, every beach club, every supplier worth knowing. They plan everything from intimate villa ceremonies to large Indian wedding weekends. What makes them different: you get two professionals working your day, an in-house stylist and florist, and a celebrant service so almost nothing needs outsourcing.",
    languages: ['English', 'Castellano'],
    based: 'Port Adriano, Mallorca',
    response: '95% within 12h',
    avgResponse: '10 hours',
    weddingsPerYear: '20+ weddings / year',
    instagram: '@awhitehotwedding',
    nextAvailable: 'Enquire for availability',
    deposit: 'Deposit on confirmation',
    badges: ['Verified'],
    photos: ['/img/togores-3.webp', '/img/comassema-3.webp', '/img/son-marroig-7.webp', '/img/couple-portrait.webp', '/img/wedding-detail.webp'],
    specialisms: [
      { ico: 'sparkles', t: 'Two planners, one day',    s: 'A partnership model — two professionals on-site means nothing gets missed.' },
      { ico: 'florist',  t: 'In-house florist & stylist', s: 'Florals, styling and décor handled in-house. Fewer suppliers, tighter design.' },
      { ico: 'sparkle',  t: 'Indian weddings',           s: 'Mallorca\'s most experienced team for multi-day Indian celebrations.' },
      { ico: 'home',     t: '20+ venues on the island',  s: 'From Son Marroig and fincas to beach clubs and private villas — we know them all.' },
    ],
    services: [
      { tier: 'Full planning', price: 'POA', popular: true,
        bullets: ['Complete end-to-end planning', 'Venue sourcing', 'Full supplier curation', 'In-house styling & florals', 'Two planners on the day', 'Legal ceremony guidance'] },
      { tier: 'Partial planning', price: 'POA',
        bullets: ['You\'ve started; we take over', 'Supplier coordination', 'Design input', 'Two planners on the day'] },
      { tier: 'On-the-day coordination', price: 'POA',
        bullets: ['Final 48 hours', 'Supplier briefings', 'Run-sheet & timeline', 'Two planners on site', 'For couples planning themselves'] },
    ],
    process: [
      { n: '01', t: 'Discovery call', s: 'We talk through your vision, your venue shortlist, and what kind of support you need.' },
      { n: '02', t: 'Proposal', s: 'A tailored proposal with our approach, timeline and fee structure.' },
      { n: '03', t: 'Planning phase', s: 'Venue, suppliers, styling and logistics — we manage every thread.' },
      { n: '04', t: 'Your day', s: 'Both of us on-site from setup to close. You enjoy every moment; we handle everything else.' },
    ],
    reviewsData: [
      { name: 'Paul Booth', date: 'May 2026', guests: 0, venue: 'Mallorca', stars: 5,
        body: 'We have recently returned from our daughter\'s wedding in Mallorca, organised by A White Hot Wedding, and had to leave a review. The team were absolutely incredible from start to finish.' },
      { name: 'Katie Betteridge', date: 'Oct 2025', guests: 0, venue: 'Mallorca', stars: 5,
        body: 'To the fabulous AWHW Team — you made our wedding day everything we dreamed of and more. Every detail was perfect and we could not have done it without you.' },
      { name: 'Vlad Bacauanu', date: 'Sep 2025', guests: 0, venue: 'Mallorca', stars: 5,
        body: 'We are so grateful to Annie, Olivia, Ode and the rest of the planning team for the immense work they put in to plan our wedding. It was truly magical.' },
      { name: 'George Stone', date: 'Sep 2025', guests: 0, venue: 'Mallorca', stars: 5,
        body: 'We met the team in 2024 with about 12 months to go until our wedding in 2025. From the outset they were supportive and professional throughout the whole process.' },
      { name: 'Ruby Wade', date: 'Aug 2025', guests: 0, venue: 'Mallorca', stars: 5,
        body: 'We first met Annie and Ode back in June 2023 when they guided us through our first venue viewings. From that moment we knew we were in safe hands.' },
      { name: 'Joyce Kim', date: 'Aug 2025', guests: 0, venue: 'Mallorca', stars: 5,
        body: 'Seamless execution, definite professionals with a great reputation across the island.' },
      { name: 'samone Winsborough', date: 'Aug 2025', guests: 0, venue: 'Finca Son Vila', stars: 5,
        body: 'We had a magical wedding at the beautiful Finca Son Vila! Being a destination wedding I cannot stress enough how important it is to have a reliable, professional team on the ground — and AWHW delivered exactly that.' },
      { name: 'Robyn Emerson', date: 'Aug 2025', guests: 0, venue: 'Mallorca', stars: 5,
        body: 'Where can I start! Annie, Olivia and the whole AWHW team made the wedding of our dreams a reality. Every single detail was taken care of with such care and professionalism.' },
    ],
    faqs: [
      { q: 'What does having two planners actually mean on the day?', a: 'One of us manages the supplier logistics and timeline; the other stays close to you and your family. Nothing falls through the gap.' },
      { q: 'Do you do Indian weddings?', a: 'Yes — we\'re one of the most experienced teams in Mallorca for multi-day Indian celebrations, including Mehndi, Sangeet and the main ceremony.' },
      { q: 'Can you handle florals and styling in-house?', a: 'Yes. We have an in-house stylist and florist, which means fewer suppliers to coordinate and a more coherent design from start to finish.' },
      { q: 'Do you work year-round?', a: 'Yes. Mallorca has become a year-round wedding destination and we plan weddings in every season.' },
    ],
    preferredVenues: ['son-marroig', 'finca-comassema', 'son-togores', 'finca-son-mir'],
    yearsActive: 20,
  },
];

export const VENUES: Venue[] = [
  {
    id: 'son-marroig', name: 'Son Marroig', region: 'Deià',
    img: '/img/son-marroig-5.webp',
    photos: ['/img/son-marroig-5.webp', '/img/son-marroig-2.webp', '/img/son-marroig-7.webp', '/img/son-marroig-9.webp', '/img/son-marroig-1.webp', '/img/son-marroig-10.webp', '/img/son-marroig-3.webp', '/img/son-marroig-6.webp', '/img/son-marroig-4.webp', '/img/son-marroig-8.webp'],
    blurb: "Iconic cliffside wedding venue near Deià, with one of the most spectacular ceremony locations in Mallorca. Son Marroig operates as a blank-canvas event space — most infrastructure is installed for each wedding, which is why totals run higher than at private fincas.",
    capacity: '60–140 guests', rentalRange: '€12,000 – €15,000', rentalMid: 13500,
    cateringTier: 'Premium', cateringPerHead: { low: 300, high: 350 }, cateringMid: 325,
    season: 'May – October', usp: 'Iconic cliffside views, Deià coast',
    tagline: 'One of the most spectacular ceremony locations in the Mediterranean.',
    plannerRequired: true, blankCanvas: true,
    costSnapshot: [
      { g: '60 guests', range: '€75,000 – €95,000' },
      { g: '80 guests', range: '€85,000 – €110,000+', highlight: true },
      { g: '120 guests', range: '€110,000 – €150,000+' },
    ],
    totalFor80: 97500, estTotal80: { low: 85000, high: 110000 },
    breakdown: [
      { item: 'Venue rental (Saturday, peak season)', value: '€12,000 – €15,000' },
      { item: 'Catering, 80 guests · premium tier', value: '€24,000 – €28,000' },
      { item: 'Infrastructure & lighting', value: '€10,000 – €15,000' },
      { item: 'Furniture & décor', value: '€8,000 – €12,000' },
      { item: 'Service & Mallorca contingency buffer', value: '€12,000 – €20,000' },
    ],
    pros: [
      "Cliff-edge marble rotunda — possibly the most photographed ceremony spot in the Mediterranean.",
      "Historic estate with cypress-lined gardens that do most of the visual work on their own.",
      "Sunset over the Med and Sa Foradada rock at 8:30pm in July, framed by the rotunda's columns.",
      "Capacity for the largest celebrations on the west coast — up to 140 inside the property.",
    ],
    things_to_know: [
      "Blank-canvas venue — most infrastructure (lighting, generators, catering kitchen) is installed per event.",
      "Wedding planner strongly recommended; many couples find it essential given the production requirements.",
      "Strict ambient-music-only rule outside; bands and DJ move into the interior party room.",
      "~40–50 minutes from Palma. No on-site accommodation.",
    ],
    whyExpensive: [
      { h: 'Cliffside location and logistics', p: "Son Marroig sits on a dramatic cliff above the Mediterranean near Deià. The location creates one of the most beautiful ceremony views in Mallorca, but requires additional planning for supplier access and transport." },
      { h: 'Blank-canvas venue', p: "The venue provides the historic setting, but most infrastructure must be installed separately for each event." },
      { h: 'Production and infrastructure', p: "Lighting rigs, generators, sound systems and catering equipment are installed specifically for the wedding day." },
      { h: 'Global demand', p: "Because of its iconic ceremony location and international reputation, Son Marroig remains one of the most sought-after wedding venues in Mallorca." },
    ],
    includes: ['Venue rental', 'Catering and open bar', 'Service staff', 'Basic infrastructure'],
    notIncluded: ['Wedding planner (€6k–€15k+)', 'Photographer / videographer (€4k–€10k)', 'Floral design (€5k–€20k+)', 'Entertainment (DJ or band)', 'Additional guest events', 'Guest transport logistics'],
    alternatives: ['son-togores', 'finca-son-mir'],
    plannerIds: ['sara', 'charlotte', 'laura'],
    metaTitle: 'Son Marroig Wedding Cost (2026 Guide) + Instant Budget Estimator',
    metaDescription: "Discover the real Son Marroig wedding cost in Mallorca for 2026. See realistic venue, catering and infrastructure budgets, hidden costs, and calculate your budget in 30 seconds.",
    slug: 'son-marroig-wedding-cost',
    listBlurb: "The island's most iconic ceremony location — a cliff-edge rotunda above the Mediterranean. A blank-canvas venue, which is why it sits at the premium end.",
    exampleBudgets: [
      { h: '80-guest wedding', range: '€90,000 – €110,000', body: 'Venue rental, premium catering, full lighting production, décor installations and guest transport coordination.' },
      { h: '120-guest wedding', range: '€120,000 – €150,000+', body: "Larger weddings reach this range because of increased catering, logistics and infrastructure requirements." },
    ],
  },
  {
    id: 'finca-comassema', name: 'Finca Comassema', region: 'Orient · Tramuntana mountains',
    img: '/img/comassema-1.webp',
    photos: ['/img/comassema-1.webp', '/img/comassema-3.webp', '/img/comassema-5.webp', '/img/comassema-9.webp', '/img/comassema-2.webp', '/img/comassema-7.webp', '/img/comassema-6.webp', '/img/comassema-4.webp', '/img/comassema-8.webp'],
    blurb: "A historic mountain estate near Orient in the Tramuntana, surrounded by olive groves and dramatic landscapes. Often chosen for larger destination weddings and multi-day celebrations because of its size and the natural backdrop.",
    capacity: '80–250 guests', rentalRange: '€10,000 – €13,000', rentalMid: 11500,
    cateringTier: 'Mid-premium', cateringPerHead: { low: 275, high: 325 }, cateringMid: 300,
    season: 'April – October', usp: 'Tramuntana mountain estate, large capacity',
    tagline: 'Mountain backdrop, room for the larger weddings.',
    plannerRequired: false, blankCanvas: false,
    costSnapshot: [
      { g: '60 guests', range: '€65,000 – €85,000' },
      { g: '80 guests', range: '€75,000 – €110,000', highlight: true },
      { g: '120 guests', range: '€100,000 – €140,000+' },
    ],
    totalFor80: 92500, estTotal80: { low: 75000, high: 110000 },
    breakdown: [
      { item: 'Venue rental (Saturday, peak)', value: '€10,000 – €13,000' },
      { item: 'Catering, 80 guests · mid-premium tier', value: '€22,000 – €26,000' },
      { item: 'Lighting & infrastructure', value: '€9,000 – €14,000' },
      { item: 'Furniture & décor', value: '€8,000 – €14,000' },
      { item: 'Service & Mallorca buffer', value: '€12,000 – €20,000' },
    ],
    pros: [
      "Spectacular mountain scenery — dramatic Tramuntana views as the visual centrepiece.",
      "Large capacity (100+ guests) — one of the few venues on the island built for genuinely big celebrations.",
      "Historic estate atmosphere — traditional architecture, courtyards, working olive groves.",
      "Flexible event spaces — multiple ceremony and reception layouts on the property.",
    ],
    things_to_know: [
      "Mountain location — additional planning needed for supplier logistics, lighting and guest transport.",
      "Books up 12–18 months ahead for peak Saturdays.",
      "Most couples bring a planner; venue scale makes solo coordination difficult.",
    ],
    whyExpensive: null,
    includes: ['Venue rental', 'Catering and open bar', 'Service staff', 'Basic infrastructure'],
    notIncluded: ['Wedding planner (€6k–€15k+)', 'Photographer / videographer (€4k–€10k)', 'Floral design (€5k–€20k+)', 'Entertainment', 'Additional events', 'Guest transport'],
    alternatives: ['finca-son-mir', 'son-togores'],
    plannerIds: ['sara', 'pau', 'laura'],
    metaTitle: 'Finca Comassema Wedding Cost (2026 Guide) + Instant Budget Estimator',
    metaDescription: "Discover the real Finca Comassema wedding cost in Mallorca for 2026. See realistic venue, catering and infrastructure budgets, hidden costs, and calculate your budget in 30 seconds.",
    slug: 'finca-comassema-wedding-cost',
    listBlurb: 'A dramatic mountain estate in the Tramuntana near Orient. Large capacity and natural scenery make it a favourite for bigger weddings and multi-day weekends.',
    exampleBudgets: [
      { h: '80-guest wedding', range: '€80,000 – €100,000', body: 'Venue, mid-premium catering, lighting and a considered design. The most common Comassema wedding.' },
      { h: '120-guest wedding', range: '€110,000 – €140,000+', body: "The venue's scale shines here — but catering, furniture and logistics rise with the guest count." },
    ],
  },
  {
    id: 'finca-son-mir', name: 'Finca Son Mir', region: 'Algaida · 20 mins from Palma',
    img: '/img/son-mir-3.webp',
    photos: ['/img/son-mir-3.webp', '/img/son-mir-1.webp', '/img/son-mir-7.webp', '/img/son-mir-5.webp', '/img/son-mir-4.webp', '/img/son-mir-2.webp', '/img/son-mir-6.webp'],
    blurb: "One of the most established wedding venues in Mallorca, just outside Palma near Algaida. Large gardens, traditional architecture and flexible event spaces — frequently chosen for destination weddings with bigger guest counts and multi-day celebrations.",
    capacity: '60–180 guests', rentalRange: '€9,000 – €12,000', rentalMid: 10500,
    cateringTier: 'Mid-range', cateringPerHead: { low: 260, high: 310 }, cateringMid: 285,
    season: 'Year-round', usp: 'Close to Palma, classic finca, large capacity',
    tagline: 'The most logistically simple of the headline fincas.',
    plannerRequired: false, blankCanvas: false,
    costSnapshot: [
      { g: '60 guests', range: '€60,000 – €80,000' },
      { g: '80 guests', range: '€70,000 – €105,000', highlight: true },
      { g: '120 guests', range: '€95,000 – €135,000+' },
    ],
    totalFor80: 87500, estTotal80: { low: 70000, high: 105000 },
    breakdown: [
      { item: 'Venue rental (Saturday, peak)', value: '€9,000 – €12,000' },
      { item: 'Catering, 80 guests · mid-range', value: '€21,000 – €25,000' },
      { item: 'Lighting & infrastructure', value: '€7,000 – €11,000' },
      { item: 'Furniture & décor', value: '€7,000 – €12,000' },
      { item: 'Service & Mallorca buffer', value: '€10,000 – €18,000' },
    ],
    pros: [
      "Large guest capacity — comfortably handles 100+ guests with spacious gardens and reception areas.",
      "Convenient location — ~20 minutes from Palma airport, easier logistics than mountain or cliffside venues.",
      "Classic finca atmosphere — traditional stone architecture and gardens, a timeless Mallorca setting.",
      "Flexible event spaces — multiple indoor and outdoor areas for different ceremony/reception formats.",
    ],
    things_to_know: [
      "Year-round availability including November/December micro-weddings.",
      "Catering and music partners are exclusive; planners work within that supplier list.",
      "Smaller dinner footprint than the headline numbers suggest — capacity sits comfortably around 80.",
    ],
    whyExpensive: null,
    includes: ['Venue rental', 'Catering and open bar', 'Service staff', 'Basic infrastructure'],
    notIncluded: ['Wedding planner (€6k–€15k+)', 'Photographer / videographer (€4k–€10k)', 'Floral design (€5k–€20k+)', 'Entertainment', 'Additional events', 'Guest transport'],
    alternatives: ['son-togores', 'finca-comassema'],
    plannerIds: ['katja', 'sara'],
    metaTitle: 'Finca Son Mir Wedding Cost (2026 Guide) + Instant Budget Estimator',
    metaDescription: "Discover the real Finca Son Mir wedding cost in Mallorca for 2026. See realistic venue, catering and infrastructure budgets, hidden costs, and calculate your budget in 30 seconds.",
    slug: 'finca-son-mir-wedding-cost',
    listBlurb: 'An established estate 20 minutes from Palma with large gardens and easy logistics — frequently chosen for bigger guest counts and weekend celebrations.',
    exampleBudgets: [
      { h: '80-guest wedding', range: '€75,000 – €95,000', body: 'Venue, mid-range catering, lighting and décor. The proximity to Palma keeps transport costs down.' },
      { h: '120-guest wedding', range: '€100,000 – €135,000+', body: 'Comfortable at this scale thanks to spacious gardens and reception areas.' },
    ],
  },
  {
    id: 'son-togores', name: 'Son Togores', region: 'Esporles · 20 mins from Palma',
    img: '/img/togores-3.webp',
    photos: ['/img/togores-3.webp', '/img/togores-1.webp', '/img/togores-9.webp', '/img/togores-2.webp', '/img/togores-5.webp', '/img/togores-6.webp', '/img/togores-4.webp', '/img/togores-7.webp', '/img/togores-8.webp'],
    blurb: "One of the most popular finca wedding venues in Mallorca. Located near Palma at the foothills of the Tramuntana, with historic architecture and gardens. Logistically simpler than cliffside venues, which often makes weddings here slightly more cost-efficient while still delivering a luxury destination wedding.",
    capacity: '40–140 guests', rentalRange: '€9,000 – €12,000', rentalMid: 10500,
    cateringTier: 'Mid-range', cateringPerHead: { low: 260, high: 310 }, cateringMid: 285,
    season: 'May – October', usp: 'Elegant finca near Palma, easier logistics',
    tagline: 'A Son Marroig atmosphere with finca-level logistics.',
    plannerRequired: false, blankCanvas: false,
    costSnapshot: [
      { g: '60 guests', range: '€60,000 – €80,000' },
      { g: '80 guests', range: '€70,000 – €100,000', highlight: true },
      { g: '120 guests', range: '€95,000 – €130,000+' },
    ],
    totalFor80: 85000, estTotal80: { low: 70000, high: 100000 },
    breakdown: [
      { item: 'Venue rental (Saturday, peak)', value: '€9,000 – €12,000' },
      { item: 'Catering, 80 guests · mid-range', value: '€21,000 – €25,000' },
      { item: 'Lighting & infrastructure', value: '€7,000 – €12,000' },
      { item: 'Furniture & décor', value: '€7,000 – €12,000' },
      { item: 'Service & Mallorca buffer', value: '€10,000 – €18,000' },
    ],
    pros: [
      "Historic finca estate — traditional Mallorcan architecture and gardens, elegant by default.",
      "Convenient location — ~20 minutes from Palma, easy guest access and supplier logistics.",
      "Lower infrastructure costs than cliffside venues — more budget for design, food, and experience.",
      "Flexible wedding layout — multiple ceremony and reception areas in the property.",
    ],
    things_to_know: [
      "Books up 14–18 months ahead for peak Saturdays.",
      "Strict supplier list — pre-approved florists and lighting partners.",
      "Indoor capacity drops to ~80 if weather forces a move.",
    ],
    whyExpensive: null,
    includes: ['Venue rental', 'Catering and open bar', 'Service staff', 'Basic infrastructure'],
    notIncluded: ['Wedding planner (€6k–€15k+)', 'Photographer / videographer (€4k–€10k)', 'Floral design (€5k–€20k+)', 'Entertainment', 'Additional events', 'Guest transport'],
    alternatives: ['finca-son-mir', 'son-marroig'],
    plannerIds: ['charlotte', 'katja'],
    metaTitle: 'Son Togores Wedding Cost (2026 Guide) + Instant Budget Estimator',
    metaDescription: "Discover the real Son Togores wedding cost in Mallorca for 2026. See realistic venue, catering and infrastructure budgets, hidden costs, and calculate your budget in 30 seconds.",
    slug: 'son-togores-wedding-cost',
    listBlurb: 'An elegant historic finca near Palma in Esporles. Logistically simpler than cliffside venues, which often makes it the more cost-efficient luxury option.',
    exampleBudgets: [
      { h: '80-guest wedding', range: '€75,000 – €95,000', body: 'Venue, mid-range catering, lighting and décor. Easier supplier access keeps infrastructure costs lower.' },
      { h: '120-guest wedding', range: '€100,000 – €130,000+', body: 'Scales well while staying below comparable cliffside venues on total production cost.' },
    ],
  },
  {
    id: 'finca-son-berga', name: 'Finca Son Berga', region: 'Alaró',
    img: '/img/comassema-1.webp',
    photos: ['/img/comassema-1.webp', '/img/comassema-6.webp', '/img/comassema-7.webp'],
    photosNote: 'Photos pending — visual stand-ins shown.',
    blurb: "A working estate in the Alaró valley — rustic luxury, deep almond groves, and one of the quieter directions on the island. Pricing benchmarks pending official cost guide.",
    capacity: '60–180 guests', rentalRange: '€8,000 – €11,000', rentalMid: 9500,
    cateringTier: 'Mid-range', cateringPerHead: { low: 250, high: 290 }, cateringMid: 270,
    season: 'April – October', usp: 'Authentic Alaró valley, rustic luxury',
    tagline: 'A quieter alternative in the Alaró valley.',
    plannerRequired: false, blankCanvas: false,
    costSnapshot: [
      { g: '60 guests', range: '€55,000 – €75,000' },
      { g: '80 guests', range: '€65,000 – €95,000', highlight: true },
      { g: '120 guests', range: '€85,000 – €120,000+' },
    ],
    totalFor80: 80000, estTotal80: { low: 65000, high: 95000 },
    breakdown: [
      { item: 'Venue rental (Saturday, peak)', value: '€8,000 – €11,000' },
      { item: 'Catering, 80 guests · mid-range', value: '€20,000 – €23,200' },
      { item: 'Lighting & infrastructure', value: '€6,000 – €11,000' },
      { item: 'Furniture & décor', value: '€6,000 – €11,000' },
      { item: 'Service & Mallorca buffer', value: '€10,000 – €18,000' },
    ],
    pros: [
      "Quieter location — fewer tourists, less Palma traffic, calm guest experience.",
      "Almond groves in full bloom February–March make for off-season magic.",
      "On-site accommodation for the closest family for the weekend.",
    ],
    things_to_know: [
      "45 minutes from Palma airport via the inland route.",
      "Spring almond blossom is a draw but evenings drop to 10°C — outdoor dinner needs heaters.",
      "Limited venue staff; planners often bring their own coordinator.",
    ],
    whyExpensive: null,
    includes: ['Venue rental', 'Catering and open bar', 'Service staff', 'Basic infrastructure'],
    notIncluded: ['Wedding planner', 'Photography', 'Florals', 'Entertainment', 'Additional events', 'Guest transport'],
    alternatives: ['finca-comassema', 'finca-son-mir'],
    plannerIds: ['marcos', 'laura'],
    metaTitle: 'Finca Son Berga Wedding Cost (2026 Guide)',
    metaDescription: "Realistic Finca Son Berga wedding cost in Mallorca for 2026. Venue, catering and infrastructure budgets, plus a free 30-second budget estimator.",
    slug: 'finca-son-berga-wedding-cost',
    listBlurb: 'A quieter working estate in the Alaró valley with almond groves and rustic luxury. One of the more affordable headline estates on the island.',
    exampleBudgets: [
      { h: '80-guest wedding', range: '€65,000 – €85,000', body: 'Venue, mid-range catering and a relaxed countryside production.' },
      { h: '120-guest wedding', range: '€85,000 – €120,000+', body: 'Scales for larger weddings while staying among the more affordable estates.' },
    ],
  },
];

export const USE_CASES: UseCase[] = [
  { key: 'luxury',    icon: 'gem',       title: 'Luxury destination weddings', body: 'Large weddings at iconic venues with complex logistics and multi-day planning.' },
  { key: 'multi-day', icon: 'sun',       title: 'Multi-day weddings',          body: 'Welcome dinners, beach events and day-after celebrations.' },
  { key: 'finca',     icon: 'home',      title: 'Finca weddings',              body: 'Private countryside weddings in traditional Mallorcan estates.' },
  { key: 'beach',     icon: 'wave',      title: 'Beach & coastal weddings',    body: 'Seaside ceremonies with Mediterranean views.' },
  { key: 'intimate',  icon: 'flame',     title: 'Intimate & elopements',       body: 'Small weddings under 40 guests — location and experience over scale.' },
  { key: 'villa',     icon: 'briefcase', title: 'Villa weddings',              body: 'Intimate weddings in private luxury villas.' },
  { key: 'indian',    icon: 'sparkles',  title: 'Indian weddings',             body: 'Multi-day ceremonies requiring specialist cultural planning.' },
  { key: 'jewish',    icon: 'star',      title: 'Jewish weddings',             body: 'Ceremonies requiring specific traditions and coordination.' },
  { key: 'lgbtq',     icon: 'rainbow',   title: 'LGBTQ+ weddings',             body: 'Inclusive destination weddings with experienced planners.' },
];

export const BLOG_POSTS: BlogPost[] = [
  { slug: 'realistic-budget-mallorca-wedding-2026', title: 'A realistic budget for a Mallorca wedding in 2026', excerpt: 'No "price on request" — actual ranges for 80-guest weddings across the most-requested fincas and cliffside venues. Most fall between €70,000 and €110,000+.', category: 'Budgeting', img: '/img/couple-hills.webp', date: '12 March 2026', readTime: '8 min read', feature: true },
  { slug: 'when-to-get-married-mallorca', title: 'When to get married in Mallorca — month-by-month', excerpt: "Heat, light, tourist crowds, and what the weather actually does in October. A planner's guide to picking your week.", category: 'Planning', img: '/img/couple-veil.webp', date: '28 April 2026', readTime: '6 min read' },
  { slug: 'finca-vs-coastal-venue', title: 'Finca or coastal venue? How to choose for your guest count', excerpt: 'A practical comparison of the two main venue archetypes — costs, weather risk, and what each one is best for.', category: 'Venues', img: '/img/couple-dancing.webp', date: '14 April 2026', readTime: '7 min read' },
  { slug: 'paperwork-civil-ceremony-spain', title: 'The paperwork: getting legally married in Spain as a UK couple', excerpt: 'Apostilles, residency timing, and why most UK couples do the legal part in a register office at home and the symbolic ceremony on the island.', category: 'Legal', img: '/img/couple-portrait.webp', date: '03 April 2026', readTime: '9 min read' },
  { slug: 'guest-experience-2-day-weekend', title: 'Designing a two-day wedding weekend your guests will remember', excerpt: 'Welcome dinner, the wedding, and the Sunday paella — how to pace the weekend without exhausting anyone.', category: 'Inspiration', img: '/img/wedding-detail.webp', date: '21 March 2026', readTime: '5 min read' },
  { slug: 'florists-stylists-mallorca', title: 'Working with Mallorca florists and stylists', excerpt: "What's in season, what to ask for, and why olive branches are everywhere (and that's fine).", category: 'Suppliers', img: '/img/couple-bouquet.webp', date: '09 March 2026', readTime: '6 min read' },
];

export const ARTICLE_BODIES: Record<string, ArticleBlock[]> = {
  'realistic-budget-mallorca-wedding-2026': [
    { type: 'p', text: "The single most common question we hear is the one no venue website seems to answer: what does a Mallorca wedding actually cost in 2026?" },
    { type: 'p', text: "We've spent two years gathering rental fees, catering tiers and supplier ranges from real weddings on the island. Here is what the maths actually looks like for an 80-guest Saturday." },
    { type: 'h2', text: 'The headline number' },
    { type: 'p', text: "Most 80-guest destination weddings in Mallorca in 2026 land between €70,000 and €110,000+ all-in for the wedding day itself — venue, catering, drinks, infrastructure, lighting, furniture, service buffer. Add €15–40k more if you're doing a welcome dinner and Sunday brunch." },
    { type: 'blockquote', text: "A mid-range finca is €70–105k for 80 guests. Son Marroig — Mallorca's most iconic cliffside venue — is €85–110k+. The variable that moves the budget most is the venue's production requirements, not the rental itself." },
    { type: 'h2', text: 'Where the money actually goes' },
    { type: 'p', text: "Catering is the largest line item — typically €21–28k for 80 guests at mid-range to premium tiers (€260–325/head). Venue rental sits at €9,000–15,000 depending on the venue tier. The surprises sit underneath: lighting and infrastructure (€7–15k), furniture and décor (€7–14k), and a Mallorca service & contingency buffer (€10–20k)." },
    { type: 'h3', text: 'A worked example: 80 guests at Finca Comassema' },
    { type: 'p', text: "Venue rental €10–13k. Catering at €275–325/head = €22–26k. Lighting & infrastructure €9–14k. Furniture & décor €8–14k. Service & buffer €12–20k. Total: €75–110k for the wedding day." },
    { type: 'p', text: "Then add a planner (€6–15k+), photography (€4–10k), florals (€5–20k+), DJ or band (€2–6k), and guest transport. The full all-in figure typically sits €25–50k above the wedding-day line — which is why most couples ask 'what was the actual final cost' and hear numbers in the €100–140k range." },
    { type: 'h2', text: 'Why Son Marroig runs higher' },
    { type: 'p', text: "Son Marroig is a 'blank-canvas' venue. The estate provides the historic setting but most production infrastructure — lighting rigs, generators, sound systems, catering kitchens, furniture — must be installed for each event. That, plus the cliffside logistics, is why Son Marroig weddings land €85–110k+ versus €70–100k at a private finca like Son Togores." },
    { type: 'h2', text: 'What couples consistently underestimate' },
    { type: 'p', text: "Three things. Guest transport — Mallorca's prettiest venues are 20–60 minutes from Palma. Drinks reception length — the gap between ceremony and dinner is where the bar tab gets uncomfortable. And the day-after — most couples want a paella lunch with whoever's still on the island." },
    { type: 'h2', text: 'How to use the matcher' },
    { type: 'p', text: "Run the free matcher with your real numbers — guest count, season, the kind of day you want. You'll get a market estimate based on the same benchmarks we use here, plus three planners who actually take weddings in your budget range." },
  ],
};

export const REAL_WEDDINGS: RealWedding[] = [
  {
    slug: 'sarah-tom-son-marroig', couple: 'Sarah & Tom',
    venueId: 'son-marroig', venueName: 'Son Marroig', region: 'Deià',
    guests: 80, date: 'Saturday 14 June 2025', month: 'June 2025',
    total: 96000, totalRange: '€92,000 – €98,000',
    plannerId: 'sara', plannerName: 'Sara Llabrés',
    style: 'Cliffside sunset · 2-day weekend',
    excerpt: "An 80-guest Saturday at the Son Marroig rotunda, with a Friday welcome dinner in Deià village and a Sunday paella for whoever stayed.",
    photos: ['/img/son-marroig-7.webp', '/img/son-marroig-10.webp', '/img/son-marroig-9.webp', '/img/son-marroig-1.webp', '/img/son-marroig-3.webp'],
    suppliers: [
      { role: 'Planner', name: 'Sara Llabrés (Slow Finca)' },
      { role: 'Photographer', name: 'Ilona Antina Photography' },
      { role: 'Florist', name: 'Citrus & Salt (Elena Mateu)' },
      { role: 'Music', name: 'String quartet + DJ' },
    ],
    breakdown: [
      { item: 'Venue rental', value: '€13,500' },
      { item: 'Catering (80g, premium)', value: '€26,400' },
      { item: 'Infrastructure & lighting', value: '€12,800' },
      { item: 'Furniture & décor', value: '€10,200' },
      { item: 'Service & buffer', value: '€14,500' },
      { item: 'Planner fee', value: '€8,500' },
      { item: 'Photography', value: '€5,800' },
      { item: 'Florals & styling', value: '€7,200' },
      { item: 'Music', value: '€4,800' },
      { item: 'Welcome dinner & Sunday paella', value: '€11,500' },
    ],
    quote: "We thought €70k was a stretch. The actual day was around €96k — and we'd do every line again.",
  },
  {
    slug: 'hollie-tom-comassema', couple: 'Hollie & Tom',
    venueId: 'finca-comassema', venueName: 'Finca Comassema', region: 'Orient · Tramuntana',
    guests: 110, date: 'Saturday 7 September 2024', month: 'September 2024',
    total: 108000, totalRange: '€104,000 – €112,000',
    plannerId: 'laura', plannerName: 'Laura · Titila',
    style: 'Mountain finca · long-table dinner',
    excerpt: "110 guests for a single long table under the Tramuntana ridge. Cocktail hour in the olive grove; dancing until 3am in the converted stable.",
    photos: ['/img/comassema-9.webp', '/img/comassema-3.webp', '/img/comassema-1.webp', '/img/comassema-5.webp', '/img/comassema-2.webp'],
    suppliers: [
      { role: 'Planner', name: 'Marc Vives (Tramuntana Days)' },
      { role: 'Photographer', name: 'Aimee K Photography' },
      { role: 'Florist', name: 'Local Orient grower' },
      { role: 'Music', name: 'Live band + DJ' },
    ],
    breakdown: [
      { item: 'Venue rental', value: '€11,500' },
      { item: 'Catering (110g, mid-premium)', value: '€30,800' },
      { item: 'Lighting & infrastructure', value: '€12,500' },
      { item: 'Furniture & décor', value: '€11,800' },
      { item: 'Service & buffer', value: '€15,200' },
      { item: 'Planner fee', value: '€9,800' },
      { item: 'Photography & video', value: '€7,400' },
      { item: 'Florals', value: '€5,200' },
      { item: 'Music', value: '€3,800' },
    ],
    quote: "The mountain view did all the heavy lifting. We spent on food and music and skipped the heavy florals.",
  },
  {
    slug: 'kate-alex-togores', couple: 'Kate & Alex',
    venueId: 'son-togores', venueName: 'Son Togores', region: 'Esporles',
    guests: 60, date: 'Saturday 21 June 2025', month: 'June 2025',
    total: 78000, totalRange: '€76,000 – €80,000',
    plannerId: 'charlotte', plannerName: 'Charlotte von Proschwitz',
    style: 'Intimate finca · courtyard dinner',
    excerpt: "60 guests, a string-light dinner in the courtyard, and a quiet ceremony under the cork oaks at the back of the estate.",
    photos: ['/img/togores-1.webp', '/img/togores-9.webp', '/img/togores-2.webp', '/img/togores-6.webp', '/img/togores-5.webp'],
    suppliers: [
      { role: 'Planner', name: 'Lina Schäfer (Costa Brava Atelier)' },
      { role: 'Photographer', name: 'Chris & Ruth Photography' },
      { role: 'Florist', name: 'Citrus & Salt' },
      { role: 'Music', name: 'Acoustic duo + DJ' },
    ],
    breakdown: [
      { item: 'Venue rental', value: '€10,500' },
      { item: 'Catering (60g, mid-range)', value: '€17,400' },
      { item: 'Lighting & infrastructure', value: '€8,200' },
      { item: 'Furniture & décor', value: '€7,800' },
      { item: 'Service & buffer', value: '€11,500' },
      { item: 'Planner fee', value: '€6,800' },
      { item: 'Photography', value: '€4,200' },
      { item: 'Florals', value: '€3,600' },
      { item: 'Music', value: '€2,800' },
    ],
    quote: "We didn't want a wedding-shaped wedding. The finca did the work; we just turned up.",
  },
];

export const EDITORIAL_TEAM: EditorialMember[] = [
  { id: 'sara', name: 'Sara Llabrés', role: 'Editor-in-chief', bio: 'Planner at Slow Finca, nine years on the island. Reviews every cost guide and planner profile.' },
  { id: 'marc', name: 'Marc Vives', role: 'Contributing editor', bio: 'Twelve years planning weddings around Sóller. Writes the Tramuntana-finca guides.' },
  { id: 'charlotte', name: 'Charlotte von Proschwitz', role: 'Contributing editor', bio: 'Fifteen years planning weddings across Mallorca. Reviews the luxury and coastal venue guides.' },
];

export const LEADS: Lead[] = [
  {
    id: 'l-001', initials: 'S&T', couple: 'Sarah & Tom', maskedName: 'S. & T.',
    received: '2h ago', receivedTs: 'Tue 14 Mar 2026 · 14:22',
    weddingDate: 'Sat 13 Jun 2026', guests: 80,
    budget: { low: 80000, high: 110000 }, budgetLabel: '€80–110k',
    venueId: 'son-marroig', venueName: 'Son Marroig', venueStatus: 'Booked',
    style: 'Luxury · cliffside sunset', priority: 'Design & atmosphere', support: 'Full-service',
    catering: 'Premium', florals: 'Elevated', photo: 'Photo + video', music: 'Live band + DJ',
    extras: ['Welcome dinner', 'Day-after brunch'], logistics: 'Medium', complexity: 6, tier: 'Mid–Lux',
    email: 's.osborne@gmail.com', phone: '+44 7700 900112',
    nationality: 'UK', languages: 'English',
    note: "We're getting married at Son Marroig in June 2026 and would love a planner who has worked there before.",
    status: 'new', unlocked: false,
  },
  {
    id: 'l-002', initials: 'D&J', couple: 'Daisy & James', maskedName: 'D. & J.',
    received: '5h ago', receivedTs: 'Tue 14 Mar 2026 · 11:08',
    weddingDate: 'Sat 12 Sep 2026', guests: 110,
    budget: { low: 110000, high: 150000 }, budgetLabel: '€110–150k',
    venueId: 'finca-comassema', venueName: 'Finca Comassema', venueStatus: 'Shortlist (3 venues)',
    style: 'Luxury · finca · multi-day', priority: 'Guest experience', support: 'Full-service',
    catering: 'Luxury', florals: 'Statement', photo: 'Photo + video', music: 'Live band + DJ',
    extras: ['Welcome dinner', 'Day-after brunch', 'Rehearsal lunch'], logistics: 'High', complexity: 9, tier: 'Luxury',
    email: 'daisy.l.howard@example.com', phone: '+44 7700 900456',
    nationality: 'UK', languages: 'English',
    note: "Three-day weekend with welcome dinner, the main day, and Sunday brunch. 110 guests, mostly flying in from London.",
    status: 'new', unlocked: false,
  },
  {
    id: 'l-003', initials: 'K&A', couple: 'Kate & Alex', maskedName: 'K. & A.',
    received: '1d ago', receivedTs: 'Mon 13 Mar 2026 · 09:30',
    weddingDate: 'Sat 19 Sep 2026', guests: 60,
    budget: { low: 70000, high: 90000 }, budgetLabel: '€70–90k',
    venueId: 'son-togores', venueName: 'Son Togores', venueStatus: 'Booked',
    style: 'Intimate · finca · courtyard', priority: 'Design & atmosphere', support: 'Partial planning',
    catering: 'Premium', florals: 'Elevated', photo: 'Photography only', music: 'DJ',
    extras: [], logistics: 'Low', complexity: 4, tier: 'Mid-range',
    email: 'kate.parker@example.com', phone: '+44 7700 900789',
    nationality: 'UK', languages: 'English · German',
    note: "Smaller wedding. We've got the venue and a photographer; need help with everything else.",
    status: 'unlocked', unlocked: true,
  },
  {
    id: 'l-004', initials: 'R&M', couple: 'Ruth & Mark', maskedName: 'R. & M.',
    received: '2d ago', receivedTs: 'Sun 12 Mar 2026 · 17:45',
    weddingDate: 'Sat 16 May 2026', guests: 40,
    budget: { low: 45000, high: 65000 }, budgetLabel: '€45–65k',
    venueId: 'finca-son-mir', venueName: 'Finca Son Mir', venueStatus: 'Booked',
    style: 'Intimate · finca', priority: 'Logistics & calm', support: 'Day-of coordination',
    catering: 'Mid-range', florals: 'Simple', photo: 'Photography only', music: 'DJ',
    extras: ['Day-after brunch'], logistics: 'Low', complexity: 2, tier: 'Coordination',
    email: 'ruth.kerridge@example.com', phone: '+44 7700 900321',
    nationality: 'UK', languages: 'English',
    note: "We're handling most of the planning ourselves but want a coordinator for the day.",
    status: 'contacted', unlocked: true,
  },
  {
    id: 'l-005', initials: 'A&M', couple: 'Aisling & Mark', maskedName: 'A. & M.',
    received: '4d ago', receivedTs: 'Fri 10 Mar 2026 · 12:14',
    weddingDate: 'Sat 18 Jul 2026', guests: 95,
    budget: { low: 90000, high: 130000 }, budgetLabel: '€90–130k',
    venueId: 'son-marroig', venueName: 'Son Marroig', venueStatus: 'Booked',
    style: 'Luxury · cliffside', priority: 'Design & atmosphere', support: 'Full-service',
    catering: 'Premium', florals: 'Statement', photo: 'Photo + video', music: 'Live band + DJ',
    extras: ['Welcome dinner'], logistics: 'Medium', complexity: 7, tier: 'Mid–Lux',
    email: 'aisling.murphy@example.com', phone: '+353 87 900 1234',
    nationality: 'Ireland', languages: 'English',
    note: "Both lawyers in Dublin. Date is set, venue is booked. Need full-service planner from this point.",
    status: 'booked', unlocked: true,
  },
];
