import type { Planner, Venue, BlogPost, ArticleBlock, RealWedding, EditorialMember, UseCase, Lead } from './types';

export const PLANNERS: Planner[] = [
  {
    id: 'sara', name: 'Sara Llabrés', firm: 'Slow Finca',
    location: 'Pollença', style: 'Finca · slow',
    types: ['finca', 'intimate'],
    guests: '20–60', minGuests: 20, maxGuests: 60,
    minBudget: 25000, maxBudget: 60000,
    season: 'Spring · autumn', price: '£8,000–14,000',
    rating: '4.96', reviews: 54, scene: 'finca',
    img: '/img/couple-hills.webp', featured: true,
    tagline: 'Small, slow weddings in the Tramuntana foothills',
    bio: "I run my family's estate just outside Pollença. The stone walls and citrus trees do most of the work — my job is to keep the rest of the day quiet, on schedule, and honest to the place. I take eight weddings a year and no more.",
    languages: ['English', 'Castellano', 'Català'],
    based: 'Pollença, Mallorca', response: '95% within 8h',
    badges: ['Verified', 'Guest favourite'],
    photos: ['/img/couple-hills.webp', '/img/wedding-detail.webp', '/img/couple-bouquet.webp', '/img/couple-portrait.webp'],
    services: [
      { title: 'Full planning', body: 'From £3,500. 12-month lead, supplier sourcing, on-the-day coordination.' },
      { title: 'Day-of coordination', body: 'From £1,400. For couples planning themselves but who want quiet hands on the day.' },
      { title: 'Venue access only', body: 'From £6,500/day. Estate hire for 40 max, with kitchen and accommodation.' },
    ],
    preferredVenues: ['son-marroig', 'finca-comassema'], yearsActive: 9,
  },
  {
    id: 'marc', name: 'Marc Vives', firm: 'Tramuntana Days',
    location: 'Sóller', style: 'Mountain · valley',
    types: ['finca', 'luxury', 'multi-day'],
    guests: '40–120', minGuests: 40, maxGuests: 120,
    minBudget: 45000, maxBudget: 130000,
    season: 'May – October', price: '£10,000–22,000',
    rating: '4.91', reviews: 38, scene: 'tramuntana',
    img: '/img/couple-dancing.webp', featured: false,
    tagline: 'Long-table dinners in the Sóller valley',
    bio: "Olive groves, the old train, lemon trees, a slow lunch into a slow evening. I plan around the season and the slope, never around a Pinterest board.",
    languages: ['English', 'Castellano'],
    based: 'Sóller, Mallorca', response: '92% within 12h',
    badges: ['Verified'],
    photos: ['/img/couple-dancing.webp', '/img/couple-portrait.webp', '/img/wedding-detail.webp'],
    services: [
      { title: 'Full planning', body: 'From £4,200. Includes venue, supplier curation, paperwork.' },
      { title: 'Two-day weddings', body: 'From £8,500. Rehearsal lunch + main day, with overnight planning.' },
    ],
    preferredVenues: ['finca-comassema', 'finca-son-berga'], yearsActive: 12,
  },
  {
    id: 'lina', name: 'Lina Schäfer', firm: 'Costa Brava Atelier',
    location: 'Cap de Formentor', style: 'Coastal · sunset',
    types: ['beach', 'luxury'],
    guests: '30–90', minGuests: 30, maxGuests: 90,
    minBudget: 55000, maxBudget: 160000,
    season: 'June – September', price: '£12,000–24,000',
    rating: '4.88', reviews: 27, scene: 'sea',
    img: '/img/couple-veil.webp', featured: true,
    tagline: 'Cliff-top ceremonies above the cap',
    bio: "I work on the north coast. Late-afternoon ceremonies, dinner under string lights, sea-facing speeches. Boats can be arranged.",
    languages: ['English', 'Castellano', 'Deutsch'],
    based: 'Port de Pollença, Mallorca', response: '88% within 24h',
    badges: ['Verified'],
    photos: ['/img/couple-veil.webp', '/img/couple-bouquet.webp', '/img/wedding-detail.webp'],
    services: [
      { title: 'Full planning', body: 'From £5,500. Coastal logistics, boat charter, sunset timing.' },
      { title: 'Coastal styling', body: 'From £2,400. Design, florals, lighting plan.' },
    ],
    preferredVenues: ['son-marroig', 'son-togores'], yearsActive: 7,
  },
  {
    id: 'rocio', name: 'Rocío Ferrer', firm: 'Palma Studio',
    location: 'Palma', style: 'Urban · courtyard',
    types: ['intimate', 'villa'],
    guests: '20–80', minGuests: 20, maxGuests: 80,
    minBudget: 22000, maxBudget: 70000,
    season: 'Year-round', price: '£7,500–16,000',
    rating: '4.94', reviews: 41, scene: 'bougainvil',
    img: '/img/couple-portrait.webp', featured: false,
    tagline: 'Old-town courtyards in the heart of Palma',
    bio: "I plan in the lanes between the cathedral and Santa Catalina. Small, refined, and warm. Many of my couples want a Friday wedding and a Saturday paella for the family.",
    languages: ['English', 'Castellano', 'Català'],
    based: 'Palma, Mallorca', response: '97% within 6h',
    badges: ['Verified'],
    photos: ['/img/couple-portrait.webp', '/img/couple-bouquet.webp', '/img/couple-dancing.webp'],
    services: [{ title: 'Full planning', body: 'From £3,800. Year-round availability, palacio paperwork, urban logistics.' }],
    preferredVenues: ['finca-son-mir'], yearsActive: 11,
  },
  {
    id: 'pau', name: 'Pau & Aina Roca', firm: 'Olive Grove Co.',
    location: 'Santanyí', style: 'Finca · long-table',
    types: ['finca', 'lgbtq', 'multi-day'],
    guests: '30–100', minGuests: 30, maxGuests: 100,
    minBudget: 32000, maxBudget: 95000,
    season: 'April – October', price: '£9,500–18,000',
    rating: '4.86', reviews: 33, scene: 'olive',
    img: '/img/wedding-detail.webp', featured: false,
    tagline: 'Long tables under 200-year-old olives',
    bio: "A small team. We do four to six weddings a year. The estate is family-owned; the food is family-cooked. We work with same-sex couples often and proudly.",
    languages: ['English', 'Castellano'],
    based: 'Santanyí, Mallorca', response: '90% within 24h',
    badges: ['Verified', 'LGBTQ+ friendly'],
    photos: ['/img/wedding-detail.webp', '/img/couple-hills.webp', '/img/couple-dancing.webp'],
    services: [
      { title: 'Full planning', body: 'From £4,000.' },
      { title: 'Multi-day weekend', body: 'From £7,800. Welcome dinner Friday, ceremony Saturday, paella lunch Sunday.' },
    ],
    preferredVenues: ['finca-son-berga', 'finca-comassema'], yearsActive: 8,
  },
  {
    id: 'elena', name: 'Elena Mateu', firm: 'Citrus & Salt',
    location: 'Valldemossa', style: 'Florist & styling',
    types: ['florist', 'intimate'],
    guests: '10–200', minGuests: 10, maxGuests: 200,
    minBudget: 8000, maxBudget: 25000,
    season: 'Year-round', price: '£1,200–4,500',
    rating: '4.99', reviews: 62, scene: 'citrus',
    img: '/img/couple-bouquet.webp', featured: true,
    tagline: 'Seasonal flowers from the Mallorcan hills',
    bio: "I source from local growers in the Tramuntana and Plà. Olive branches, citrus blossom, soft-coloured roses, herbs. I keep everything close to the land.",
    languages: ['English', 'Castellano'],
    based: 'Valldemossa, Mallorca', response: '98% within 4h',
    badges: ['Verified', 'Guest favourite'],
    photos: ['/img/couple-bouquet.webp', '/img/wedding-detail.webp', '/img/couple-veil.webp'],
    services: [
      { title: 'Wedding florals', body: 'From £1,400. Bouquets, ceremony, long-table installation.' },
      { title: 'Full styling', body: 'From £3,200. Tablescapes, lighting, signage, paper goods.' },
    ],
    preferredVenues: ['son-marroig'], yearsActive: 6,
  },
];

export const VENUES: Venue[] = [
  {
    id: 'son-marroig', name: 'Son Marroig', region: 'Deià',
    img: '/img/son-marroig-5.webp',
    photos: ['/img/son-marroig-5.webp', '/img/son-marroig-2.webp', '/img/son-marroig-7.webp', '/img/son-marroig-9.webp', '/img/son-marroig-1.webp', '/img/son-marroig-10.webp', '/img/son-marroig-3.webp', '/img/son-marroig-6.webp', '/img/son-marroig-4.webp', '/img/son-marroig-8.webp'],
    blurb: "Iconic cliffside wedding venue near Deià, with one of the most spectacular ceremony locations in Mallorca. Son Marroig operates as a blank-canvas event space — most infrastructure is installed for each wedding, which is why totals run higher than at private fincas.",
    capacity: '60–140 guests', rentalRange: '€12,000 – €15,000', rentalMid: 13500,
    cateringTier: 'Premium', cateringPerHead: { low: 300, high: 350 }, cateringMid: 325,
    season: 'May – October', usp: 'Iconic cliffside views, Deià coast',
    tagline: 'One of the most spectacular ceremony locations in the Mediterranean.',
    plannerRequired: true, blankCanvas: true,
    costSnapshot: [
      { g: '60 guests', range: '€75,000 – €95,000' },
      { g: '80 guests', range: '€85,000 – €110,000+', highlight: true },
      { g: '120 guests', range: '€110,000 – €150,000+' },
    ],
    totalFor80: 97500, estTotal80: { low: 85000, high: 110000 },
    breakdown: [
      { item: 'Venue rental (Saturday, peak season)', value: '€12,000 – €15,000' },
      { item: 'Catering, 80 guests · premium tier', value: '€24,000 – €28,000' },
      { item: 'Infrastructure & lighting', value: '€10,000 – €15,000' },
      { item: 'Furniture & décor', value: '€8,000 – €12,000' },
      { item: 'Service & Mallorca contingency buffer', value: '€12,000 – €20,000' },
    ],
    pros: [
      "Cliff-edge marble rotunda — possibly the most photographed ceremony spot in the Mediterranean.",
      "Historic estate with cypress-lined gardens that do most of the visual work on their own.",
      "Sunset over the Med and Sa Foradada rock at 8:30pm in July, framed by the rotunda's columns.",
      "Capacity for the largest celebrations on the west coast — up to 140 inside the property.",
    ],
    things_to_know: [
      "Blank-canvas venue — most infrastructure (lighting, generators, catering kitchen) is installed per event.",
      "Wedding planner strongly recommended; many couples find it essential given the production requirements.",
      "Strict ambient-music-only rule outside; bands and DJ move into the interior party room.",
      "~40–50 minutes from Palma. No on-site accommodation.",
    ],
    whyExpensive: [
      { h: 'Cliffside location and logistics', p: "Son Marroig sits on a dramatic cliff above the Mediterranean near Deià. The location creates one of the most beautiful ceremony views in Mallorca, but requires additional planning for supplier access and transport." },
      { h: 'Blank-canvas venue', p: "The venue provides the historic setting, but most infrastructure must be installed separately for each event." },
      { h: 'Production and infrastructure', p: "Lighting rigs, generators, sound systems and catering equipment are installed specifically for the wedding day." },
      { h: 'Global demand', p: "Because of its iconic ceremony location and international reputation, Son Marroig remains one of the most sought-after wedding venues in Mallorca." },
    ],
    includes: ['Venue rental', 'Catering and open bar', 'Service staff', 'Basic infrastructure'],
    notIncluded: ['Wedding planner (€6k–€15k+)', 'Photographer / videographer (€4k–€10k)', 'Floral design (€5k–€20k+)', 'Entertainment (DJ or band)', 'Additional guest events', 'Guest transport logistics'],
    alternatives: ['son-togores', 'finca-son-mir'],
    plannerIds: ['sara', 'lina', 'marc'],
    metaTitle: 'Son Marroig Wedding Cost (2026 Guide) + Instant Budget Estimator',
    metaDescription: "Discover the real Son Marroig wedding cost in Mallorca for 2026. See realistic venue, catering and infrastructure budgets, hidden costs, and calculate your budget in 30 seconds.",
  },
  {
    id: 'finca-comassema', name: 'Finca Comassema', region: 'Orient · Tramuntana mountains',
    img: '/img/comassema-1.webp',
    photos: ['/img/comassema-1.webp', '/img/comassema-3.webp', '/img/comassema-5.webp', '/img/comassema-9.webp', '/img/comassema-2.webp', '/img/comassema-7.webp', '/img/comassema-6.webp', '/img/comassema-4.webp', '/img/comassema-8.webp'],
    blurb: "A historic mountain estate near Orient in the Tramuntana, surrounded by olive groves and dramatic landscapes. Often chosen for larger destination weddings and multi-day celebrations because of its size and the natural backdrop.",
    capacity: '80–250 guests', rentalRange: '€10,000 – €13,000', rentalMid: 11500,
    cateringTier: 'Mid-premium', cateringPerHead: { low: 275, high: 325 }, cateringMid: 300,
    season: 'April – October', usp: 'Tramuntana mountain estate, large capacity',
    tagline: 'Mountain backdrop, room for the larger weddings.',
    plannerRequired: false, blankCanvas: false,
    costSnapshot: [
      { g: '60 guests', range: '€65,000 – €85,000' },
      { g: '80 guests', range: '€75,000 – €110,000', highlight: true },
      { g: '120 guests', range: '€100,000 – €140,000+' },
    ],
    totalFor80: 92500, estTotal80: { low: 75000, high: 110000 },
    breakdown: [
      { item: 'Venue rental (Saturday, peak)', value: '€10,000 – €13,000' },
      { item: 'Catering, 80 guests · mid-premium tier', value: '€22,000 – €26,000' },
      { item: 'Lighting & infrastructure', value: '€9,000 – €14,000' },
      { item: 'Furniture & décor', value: '€8,000 – €14,000' },
      { item: 'Service & Mallorca buffer', value: '€12,000 – €20,000' },
    ],
    pros: [
      "Spectacular mountain scenery — dramatic Tramuntana views as the visual centrepiece.",
      "Large capacity (100+ guests) — one of the few venues on the island built for genuinely big celebrations.",
      "Historic estate atmosphere — traditional architecture, courtyards, working olive groves.",
      "Flexible event spaces — multiple ceremony and reception layouts on the property.",
    ],
    things_to_know: [
      "Mountain location — additional planning needed for supplier logistics, lighting and guest transport.",
      "Books up 12–18 months ahead for peak Saturdays.",
      "Most couples bring a planner; venue scale makes solo coordination difficult.",
    ],
    whyExpensive: null,
    includes: ['Venue rental', 'Catering and open bar', 'Service staff', 'Basic infrastructure'],
    notIncluded: ['Wedding planner (€6k–€15k+)', 'Photographer / videographer (€4k–€10k)', 'Floral design (€5k–€20k+)', 'Entertainment', 'Additional events', 'Guest transport'],
    alternatives: ['finca-son-mir', 'son-togores'],
    plannerIds: ['sara', 'pau', 'marc'],
    metaTitle: 'Finca Comassema Wedding Cost (2026 Guide) + Instant Budget Estimator',
    metaDescription: "Discover the real Finca Comassema wedding cost in Mallorca for 2026. See realistic venue, catering and infrastructure budgets, hidden costs, and calculate your budget in 30 seconds.",
  },
  {
    id: 'finca-son-mir', name: 'Finca Son Mir', region: 'Algaida · 20 mins from Palma',
    img: '/img/son-mir-3.webp',
    photos: ['/img/son-mir-3.webp', '/img/son-mir-1.webp', '/img/son-mir-7.webp', '/img/son-mir-5.webp', '/img/son-mir-4.webp', '/img/son-mir-2.webp', '/img/son-mir-6.webp'],
    blurb: "One of the most established wedding venues in Mallorca, just outside Palma near Algaida. Large gardens, traditional architecture and flexible event spaces — frequently chosen for destination weddings with bigger guest counts and multi-day celebrations.",
    capacity: '60–180 guests', rentalRange: '€9,000 – €12,000', rentalMid: 10500,
    cateringTier: 'Mid-range', cateringPerHead: { low: 260, high: 310 }, cateringMid: 285,
    season: 'Year-round', usp: 'Close to Palma, classic finca, large capacity',
    tagline: 'The most logistically simple of the headline fincas.',
    plannerRequired: false, blankCanvas: false,
    costSnapshot: [
      { g: '60 guests', range: '€60,000 – €80,000' },
      { g: '80 guests', range: '€70,000 – €105,000', highlight: true },
      { g: '120 guests', range: '€95,000 – €135,000+' },
    ],
    totalFor80: 87500, estTotal80: { low: 70000, high: 105000 },
    breakdown: [
      { item: 'Venue rental (Saturday, peak)', value: '€9,000 – €12,000' },
      { item: 'Catering, 80 guests · mid-range', value: '€21,000 – €25,000' },
      { item: 'Lighting & infrastructure', value: '€7,000 – €11,000' },
      { item: 'Furniture & décor', value: '€7,000 – €12,000' },
      { item: 'Service & Mallorca buffer', value: '€10,000 – €18,000' },
    ],
    pros: [
      "Large guest capacity — comfortably handles 100+ guests with spacious gardens and reception areas.",
      "Convenient location — ~20 minutes from Palma airport, easier logistics than mountain or cliffside venues.",
      "Classic finca atmosphere — traditional stone architecture and gardens, a timeless Mallorca setting.",
      "Flexible event spaces — multiple indoor and outdoor areas for different ceremony/reception formats.",
    ],
    things_to_know: [
      "Year-round availability including November/December micro-weddings.",
      "Catering and music partners are exclusive; planners work within that supplier list.",
      "Smaller dinner footprint than the headline numbers suggest — capacity sits comfortably around 80.",
    ],
    whyExpensive: null,
    includes: ['Venue rental', 'Catering and open bar', 'Service staff', 'Basic infrastructure'],
    notIncluded: ['Wedding planner (€6k–€15k+)', 'Photographer / videographer (€4k–€10k)', 'Floral design (€5k–€20k+)', 'Entertainment', 'Additional events', 'Guest transport'],
    alternatives: ['son-togores', 'finca-comassema'],
    plannerIds: ['rocio', 'sara'],
    metaTitle: 'Finca Son Mir Wedding Cost (2026 Guide) + Instant Budget Estimator',
    metaDescription: "Discover the real Finca Son Mir wedding cost in Mallorca for 2026. See realistic venue, catering and infrastructure budgets, hidden costs, and calculate your budget in 30 seconds.",
  },
  {
    id: 'son-togores', name: 'Son Togores', region: 'Esporles · 20 mins from Palma',
    img: '/img/togores-3.webp',
    photos: ['/img/togores-3.webp', '/img/togores-1.webp', '/img/togores-9.webp', '/img/togores-2.webp', '/img/togores-5.webp', '/img/togores-6.webp', '/img/togores-4.webp', '/img/togores-7.webp', '/img/togores-8.webp'],
    blurb: "One of the most popular finca wedding venues in Mallorca. Located near Palma at the foothills of the Tramuntana, with historic architecture and gardens. Logistically simpler than cliffside venues, which often makes weddings here slightly more cost-efficient while still delivering a luxury destination wedding.",
    capacity: '40–140 guests', rentalRange: '€9,000 – €12,000', rentalMid: 10500,
    cateringTier: 'Mid-range', cateringPerHead: { low: 260, high: 310 }, cateringMid: 285,
    season: 'May – October', usp: 'Elegant finca near Palma, easier logistics',
    tagline: 'A Son Marroig atmosphere with finca-level logistics.',
    plannerRequired: false, blankCanvas: false,
    costSnapshot: [
      { g: '60 guests', range: '€60,000 – €80,000' },
      { g: '80 guests', range: '€70,000 – €100,000', highlight: true },
      { g: '120 guests', range: '€95,000 – €130,000+' },
    ],
    totalFor80: 85000, estTotal80: { low: 70000, high: 100000 },
    breakdown: [
      { item: 'Venue rental (Saturday, peak)', value: '€9,000 – €12,000' },
      { item: 'Catering, 80 guests · mid-range', value: '€21,000 – €25,000' },
      { item: 'Lighting & infrastructure', value: '€7,000 – €12,000' },
      { item: 'Furniture & décor', value: '€7,000 – €12,000' },
      { item: 'Service & Mallorca buffer', value: '€10,000 – €18,000' },
    ],
    pros: [
      "Historic finca estate — traditional Mallorcan architecture and gardens, elegant by default.",
      "Convenient location — ~20 minutes from Palma, easy guest access and supplier logistics.",
      "Lower infrastructure costs than cliffside venues — more budget for design, food, and experience.",
      "Flexible wedding layout — multiple ceremony and reception areas in the property.",
    ],
    things_to_know: [
      "Books up 14–18 months ahead for peak Saturdays.",
      "Strict supplier list — pre-approved florists and lighting partners.",
      "Indoor capacity drops to ~80 if weather forces a move.",
    ],
    whyExpensive: null,
    includes: ['Venue rental', 'Catering and open bar', 'Service staff', 'Basic infrastructure'],
    notIncluded: ['Wedding planner (€6k–€15k+)', 'Photographer / videographer (€4k–€10k)', 'Floral design (€5k–€20k+)', 'Entertainment', 'Additional events', 'Guest transport'],
    alternatives: ['finca-son-mir', 'son-marroig'],
    plannerIds: ['lina', 'rocio'],
    metaTitle: 'Son Togores Wedding Cost (2026 Guide) + Instant Budget Estimator',
    metaDescription: "Discover the real Son Togores wedding cost in Mallorca for 2026. See realistic venue, catering and infrastructure budgets, hidden costs, and calculate your budget in 30 seconds.",
  },
  {
    id: 'finca-son-berga', name: 'Finca Son Berga', region: 'Alaró',
    img: '/img/comassema-1.webp',
    photos: ['/img/comassema-1.webp', '/img/comassema-6.webp', '/img/comassema-7.webp'],
    photosNote: 'Photos pending — visual stand-ins shown.',
    blurb: "A working estate in the Alaró valley — rustic luxury, deep almond groves, and one of the quieter directions on the island. Pricing benchmarks pending official cost guide.",
    capacity: '60–180 guests', rentalRange: '€8,000 – €11,000', rentalMid: 9500,
    cateringTier: 'Mid-range', cateringPerHead: { low: 250, high: 290 }, cateringMid: 270,
    season: 'April – October', usp: 'Authentic Alaró valley, rustic luxury',
    tagline: 'A quieter alternative in the Alaró valley.',
    plannerRequired: false, blankCanvas: false,
    costSnapshot: [
      { g: '60 guests', range: '€55,000 – €75,000' },
      { g: '80 guests', range: '€65,000 – €95,000', highlight: true },
      { g: '120 guests', range: '€85,000 – €120,000+' },
    ],
    totalFor80: 80000, estTotal80: { low: 65000, high: 95000 },
    breakdown: [
      { item: 'Venue rental (Saturday, peak)', value: '€8,000 – €11,000' },
      { item: 'Catering, 80 guests · mid-range', value: '€20,000 – €23,200' },
      { item: 'Lighting & infrastructure', value: '€6,000 – €11,000' },
      { item: 'Furniture & décor', value: '€6,000 – €11,000' },
      { item: 'Service & Mallorca buffer', value: '€10,000 – €18,000' },
    ],
    pros: [
      "Quieter location — fewer tourists, less Palma traffic, calm guest experience.",
      "Almond groves in full bloom February–March make for off-season magic.",
      "On-site accommodation for the closest family for the weekend.",
    ],
    things_to_know: [
      "45 minutes from Palma airport via the inland route.",
      "Spring almond blossom is a draw but evenings drop to 10°C — outdoor dinner needs heaters.",
      "Limited venue staff; planners often bring their own coordinator.",
    ],
    whyExpensive: null,
    includes: ['Venue rental', 'Catering and open bar', 'Service staff', 'Basic infrastructure'],
    notIncluded: ['Wedding planner', 'Photography', 'Florals', 'Entertainment', 'Additional events', 'Guest transport'],
    alternatives: ['finca-comassema', 'finca-son-mir'],
    plannerIds: ['pau', 'marc'],
    metaTitle: 'Finca Son Berga Wedding Cost (2026 Guide)',
    metaDescription: "Realistic Finca Son Berga wedding cost in Mallorca for 2026. Venue, catering and infrastructure budgets, plus a free 30-second budget estimator.",
  },
];

export const USE_CASES: UseCase[] = [
  { key: 'luxury',    icon: 'gem',       title: 'Luxury destination weddings', body: 'Large weddings at iconic venues with complex logistics and multi-day planning.' },
  { key: 'multi-day', icon: 'sun',       title: 'Multi-day weddings',          body: 'Welcome dinners, beach events and day-after celebrations.' },
  { key: 'finca',     icon: 'home',      title: 'Finca weddings',              body: 'Private countryside weddings in traditional Mallorcan estates.' },
  { key: 'beach',     icon: 'wave',      title: 'Beach & coastal weddings',    body: 'Seaside ceremonies with Mediterranean views.' },
  { key: 'intimate',  icon: 'flame',     title: 'Intimate & elopements',       body: 'Small weddings under 40 guests — location and experience over scale.' },
  { key: 'villa',     icon: 'briefcase', title: 'Villa weddings',              body: 'Intimate weddings in private luxury villas.' },
  { key: 'indian',    icon: 'sparkles',  title: 'Indian weddings',             body: 'Multi-day ceremonies requiring specialist cultural planning.' },
  { key: 'jewish',    icon: 'star',      title: 'Jewish weddings',             body: 'Ceremonies requiring specific traditions and coordination.' },
  { key: 'lgbtq',     icon: 'rainbow',   title: 'LGBTQ+ weddings',             body: 'Inclusive destination weddings with experienced planners.' },
];

export const BLOG_POSTS: BlogPost[] = [
  { slug: 'realistic-budget-mallorca-wedding-2026', title: 'A realistic budget for a Mallorca wedding in 2026', excerpt: 'No "price on request" — actual ranges for 80-guest weddings across the most-requested fincas and cliffside venues. Most fall between €70,000 and €110,000+.', category: 'Budgeting', img: '/img/couple-hills.webp', date: '12 March 2026', readTime: '8 min read', feature: true },
  { slug: 'when-to-get-married-mallorca', title: 'When to get married in Mallorca — month-by-month', excerpt: "Heat, light, tourist crowds, and what the weather actually does in October. A planner's guide to picking your week.", category: 'Planning', img: '/img/couple-veil.webp', date: '28 April 2026', readTime: '6 min read' },
  { slug: 'finca-vs-coastal-venue', title: 'Finca or coastal venue? How to choose for your guest count', excerpt: 'A practical comparison of the two main venue archetypes — costs, weather risk, and what each one is best for.', category: 'Venues', img: '/img/couple-dancing.webp', date: '14 April 2026', readTime: '7 min read' },
  { slug: 'paperwork-civil-ceremony-spain', title: 'The paperwork: getting legally married in Spain as a UK couple', excerpt: 'Apostilles, residency timing, and why most UK couples do the legal part in a register office at home and the symbolic ceremony on the island.', category: 'Legal', img: '/img/couple-portrait.webp', date: '03 April 2026', readTime: '9 min read' },
  { slug: 'guest-experience-2-day-weekend', title: 'Designing a two-day wedding weekend your guests will remember', excerpt: 'Welcome dinner, the wedding, and the Sunday paella — how to pace the weekend without exhausting anyone.', category: 'Inspiration', img: '/img/wedding-detail.webp', date: '21 March 2026', readTime: '5 min read' },
  { slug: 'florists-stylists-mallorca', title: 'Working with Mallorca florists and stylists', excerpt: "What's in season, what to ask for, and why olive branches are everywhere (and that's fine).", category: 'Suppliers', img: '/img/couple-bouquet.webp', date: '09 March 2026', readTime: '6 min read' },
];

export const ARTICLE_BODIES: Record<string, ArticleBlock[]> = {
  'realistic-budget-mallorca-wedding-2026': [
    { type: 'p', text: "The single most common question we hear is the one no venue website seems to answer: what does a Mallorca wedding actually cost in 2026?" },
    { type: 'p', text: "We've spent two years gathering rental fees, catering tiers and supplier ranges from real weddings on the island. Here is what the maths actually looks like for an 80-guest Saturday." },
    { type: 'h2', text: 'The headline number' },
    { type: 'p', text: "Most 80-guest destination weddings in Mallorca in 2026 land between €70,000 and €110,000+ all-in for the wedding day itself — venue, catering, drinks, infrastructure, lighting, furniture, service buffer. Add €15–40k more if you're doing a welcome dinner and Sunday brunch." },
    { type: 'blockquote', text: "A mid-range finca is €70–105k for 80 guests. Son Marroig — Mallorca's most iconic cliffside venue — is €85–110k+. The variable that moves the budget most is the venue's production requirements, not the rental itself." },
    { type: 'h2', text: 'Where the money actually goes' },
    { type: 'p', text: "Catering is the largest line item — typically €21–28k for 80 guests at mid-range to premium tiers (€260–325/head). Venue rental sits at €9,000–15,000 depending on the venue tier. The surprises sit underneath: lighting and infrastructure (€7–15k), furniture and décor (€7–14k), and a Mallorca service & contingency buffer (€10–20k)." },
    { type: 'h3', text: 'A worked example: 80 guests at Finca Comassema' },
    { type: 'p', text: "Venue rental €10–13k. Catering at €275–325/head = €22–26k. Lighting & infrastructure €9–14k. Furniture & décor €8–14k. Service & buffer €12–20k. Total: €75–110k for the wedding day." },
    { type: 'p', text: "Then add a planner (€6–15k+), photography (€4–10k), florals (€5–20k+), DJ or band (€2–6k), and guest transport. The full all-in figure typically sits €25–50k above the wedding-day line — which is why most couples ask 'what was the actual final cost' and hear numbers in the €100–140k range." },
    { type: 'h2', text: 'Why Son Marroig runs higher' },
    { type: 'p', text: "Son Marroig is a 'blank-canvas' venue. The estate provides the historic setting but most production infrastructure — lighting rigs, generators, sound systems, catering kitchens, furniture — must be installed for each event. That, plus the cliffside logistics, is why Son Marroig weddings land €85–110k+ versus €70–100k at a private finca like Son Togores." },
    { type: 'h2', text: 'What couples consistently underestimate' },
    { type: 'p', text: "Three things. Guest transport — Mallorca's prettiest venues are 20–60 minutes from Palma. Drinks reception length — the gap between ceremony and dinner is where the bar tab gets uncomfortable. And the day-after — most couples want a paella lunch with whoever's still on the island." },
    { type: 'h2', text: 'How to use the matcher' },
    { type: 'p', text: "Run the free matcher with your real numbers — guest count, season, the kind of day you want. You'll get a market estimate based on the same benchmarks we use here, plus three planners who actually take weddings in your budget range." },
  ],
};

export const REAL_WEDDINGS: RealWedding[] = [
  {
    slug: 'sarah-tom-son-marroig', couple: 'Sarah & Tom',
    venueId: 'son-marroig', venueName: 'Son Marroig', region: 'Deià',
    guests: 80, date: 'Saturday 14 June 2025', month: 'June 2025',
    total: 96000, totalRange: '€92,000 – €98,000',
    plannerId: 'sara', plannerName: 'Sara Llabrés',
    style: 'Cliffside sunset · 2-day weekend',
    excerpt: "An 80-guest Saturday at the Son Marroig rotunda, with a Friday welcome dinner in Deià village and a Sunday paella for whoever stayed.",
    photos: ['/img/son-marroig-7.webp', '/img/son-marroig-10.webp', '/img/son-marroig-9.webp', '/img/son-marroig-1.webp', '/img/son-marroig-3.webp'],
    suppliers: [
      { role: 'Planner', name: 'Sara Llabrés (Slow Finca)' },
      { role: 'Photographer', name: 'Ilona Antina Photography' },
      { role: 'Florist', name: 'Citrus & Salt (Elena Mateu)' },
      { role: 'Music', name: 'String quartet + DJ' },
    ],
    breakdown: [
      { item: 'Venue rental', value: '€13,500' },
      { item: 'Catering (80g, premium)', value: '€26,400' },
      { item: 'Infrastructure & lighting', value: '€12,800' },
      { item: 'Furniture & décor', value: '€10,200' },
      { item: 'Service & buffer', value: '€14,500' },
      { item: 'Planner fee', value: '€8,500' },
      { item: 'Photography', value: '€5,800' },
      { item: 'Florals & styling', value: '€7,200' },
      { item: 'Music', value: '€4,800' },
      { item: 'Welcome dinner & Sunday paella', value: '€11,500' },
    ],
    quote: "We thought €70k was a stretch. The actual day was around €96k — and we'd do every line again.",
  },
  {
    slug: 'hollie-tom-comassema', couple: 'Hollie & Tom',
    venueId: 'finca-comassema', venueName: 'Finca Comassema', region: 'Orient · Tramuntana',
    guests: 110, date: 'Saturday 7 September 2024', month: 'September 2024',
    total: 108000, totalRange: '€104,000 – €112,000',
    plannerId: 'marc', plannerName: 'Marc Vives',
    style: 'Mountain finca · long-table dinner',
    excerpt: "110 guests for a single long table under the Tramuntana ridge. Cocktail hour in the olive grove; dancing until 3am in the converted stable.",
    photos: ['/img/comassema-9.webp', '/img/comassema-3.webp', '/img/comassema-1.webp', '/img/comassema-5.webp', '/img/comassema-2.webp'],
    suppliers: [
      { role: 'Planner', name: 'Marc Vives (Tramuntana Days)' },
      { role: 'Photographer', name: 'Aimee K Photography' },
      { role: 'Florist', name: 'Local Orient grower' },
      { role: 'Music', name: 'Live band + DJ' },
    ],
    breakdown: [
      { item: 'Venue rental', value: '€11,500' },
      { item: 'Catering (110g, mid-premium)', value: '€30,800' },
      { item: 'Lighting & infrastructure', value: '€12,500' },
      { item: 'Furniture & décor', value: '€11,800' },
      { item: 'Service & buffer', value: '€15,200' },
      { item: 'Planner fee', value: '€9,800' },
      { item: 'Photography & video', value: '€7,400' },
      { item: 'Florals', value: '€5,200' },
      { item: 'Music', value: '€3,800' },
    ],
    quote: "The mountain view did all the heavy lifting. We spent on food and music and skipped the heavy florals.",
  },
  {
    slug: 'kate-alex-togores', couple: 'Kate & Alex',
    venueId: 'son-togores', venueName: 'Son Togores', region: 'Esporles',
    guests: 60, date: 'Saturday 21 June 2025', month: 'June 2025',
    total: 78000, totalRange: '€76,000 – €80,000',
    plannerId: 'lina', plannerName: 'Lina Schäfer',
    style: 'Intimate finca · courtyard dinner',
    excerpt: "60 guests, a string-light dinner in the courtyard, and a quiet ceremony under the cork oaks at the back of the estate.",
    photos: ['/img/togores-1.webp', '/img/togores-9.webp', '/img/togores-2.webp', '/img/togores-6.webp', '/img/togores-5.webp'],
    suppliers: [
      { role: 'Planner', name: 'Lina Schäfer (Costa Brava Atelier)' },
      { role: 'Photographer', name: 'Chris & Ruth Photography' },
      { role: 'Florist', name: 'Citrus & Salt' },
      { role: 'Music', name: 'Acoustic duo + DJ' },
    ],
    breakdown: [
      { item: 'Venue rental', value: '€10,500' },
      { item: 'Catering (60g, mid-range)', value: '€17,400' },
      { item: 'Lighting & infrastructure', value: '€8,200' },
      { item: 'Furniture & décor', value: '€7,800' },
      { item: 'Service & buffer', value: '€11,500' },
      { item: 'Planner fee', value: '€6,800' },
      { item: 'Photography', value: '€4,200' },
      { item: 'Florals', value: '€3,600' },
      { item: 'Music', value: '€2,800' },
    ],
    quote: "We didn't want a wedding-shaped wedding. The finca did the work; we just turned up.",
  },
];

export const EDITORIAL_TEAM: EditorialMember[] = [
  { id: 'sara', name: 'Sara Llabrés', role: 'Editor-in-chief', bio: 'Planner at Slow Finca, nine years on the island. Reviews every cost guide and planner profile.' },
  { id: 'marc', name: 'Marc Vives', role: 'Contributing editor', bio: 'Twelve years planning weddings around Sóller. Writes the Tramuntana-finca guides.' },
  { id: 'lina', name: 'Lina Schäfer', role: 'Coastal weddings editor', bio: 'Seven years planning weddings on the north coast. Reviews the cliffside venue guides.' },
];

export const LEADS: Lead[] = [
  {
    id: 'l-001', initials: 'S&T', couple: 'Sarah & Tom', maskedName: 'S. & T.',
    received: '2h ago', receivedTs: 'Tue 14 Mar 2026 · 14:22',
    weddingDate: 'Sat 13 Jun 2026', guests: 80,
    budget: { low: 80000, high: 110000 }, budgetLabel: '€80–110k',
    venueId: 'son-marroig', venueName: 'Son Marroig', venueStatus: 'Booked',
    style: 'Luxury · cliffside sunset', priority: 'Design & atmosphere', support: 'Full-service',
    catering: 'Premium', florals: 'Elevated', photo: 'Photo + video', music: 'Live band + DJ',
    extras: ['Welcome dinner', 'Day-after brunch'], logistics: 'Medium', complexity: 6, tier: 'Mid–Lux',
    email: 's.osborne@gmail.com', phone: '+44 7700 900112',
    nationality: 'UK', languages: 'English',
    note: "We're getting married at Son Marroig in June 2026 and would love a planner who has worked there before.",
    status: 'new', unlocked: false,
  },
  {
    id: 'l-002', initials: 'D&J', couple: 'Daisy & James', maskedName: 'D. & J.',
    received: '5h ago', receivedTs: 'Tue 14 Mar 2026 · 11:08',
    weddingDate: 'Sat 12 Sep 2026', guests: 110,
    budget: { low: 110000, high: 150000 }, budgetLabel: '€110–150k',
    venueId: 'finca-comassema', venueName: 'Finca Comassema', venueStatus: 'Shortlist (3 venues)',
    style: 'Luxury · finca · multi-day', priority: 'Guest experience', support: 'Full-service',
    catering: 'Luxury', florals: 'Statement', photo: 'Photo + video', music: 'Live band + DJ',
    extras: ['Welcome dinner', 'Day-after brunch', 'Rehearsal lunch'], logistics: 'High', complexity: 9, tier: 'Luxury',
    email: 'daisy.l.howard@example.com', phone: '+44 7700 900456',
    nationality: 'UK', languages: 'English',
    note: "Three-day weekend with welcome dinner, the main day, and Sunday brunch. 110 guests, mostly flying in from London.",
    status: 'new', unlocked: false,
  },
  {
    id: 'l-003', initials: 'K&A', couple: 'Kate & Alex', maskedName: 'K. & A.',
    received: '1d ago', receivedTs: 'Mon 13 Mar 2026 · 09:30',
    weddingDate: 'Sat 19 Sep 2026', guests: 60,
    budget: { low: 70000, high: 90000 }, budgetLabel: '€70–90k',
    venueId: 'son-togores', venueName: 'Son Togores', venueStatus: 'Booked',
    style: 'Intimate · finca · courtyard', priority: 'Design & atmosphere', support: 'Partial planning',
    catering: 'Premium', florals: 'Elevated', photo: 'Photography only', music: 'DJ',
    extras: [], logistics: 'Low', complexity: 4, tier: 'Mid-range',
    email: 'kate.parker@example.com', phone: '+44 7700 900789',
    nationality: 'UK', languages: 'English · German',
    note: "Smaller wedding. We've got the venue and a photographer; need help with everything else.",
    status: 'unlocked', unlocked: true,
  },
  {
    id: 'l-004', initials: 'R&M', couple: 'Ruth & Mark', maskedName: 'R. & M.',
    received: '2d ago', receivedTs: 'Sun 12 Mar 2026 · 17:45',
    weddingDate: 'Sat 16 May 2026', guests: 40,
    budget: { low: 45000, high: 65000 }, budgetLabel: '€45–65k',
    venueId: 'finca-son-mir', venueName: 'Finca Son Mir', venueStatus: 'Booked',
    style: 'Intimate · finca', priority: 'Logistics & calm', support: 'Day-of coordination',
    catering: 'Mid-range', florals: 'Simple', photo: 'Photography only', music: 'DJ',
    extras: ['Day-after brunch'], logistics: 'Low', complexity: 2, tier: 'Coordination',
    email: 'ruth.kerridge@example.com', phone: '+44 7700 900321',
    nationality: 'UK', languages: 'English',
    note: "We're handling most of the planning ourselves but want a coordinator for the day.",
    status: 'contacted', unlocked: true,
  },
  {
    id: 'l-005', initials: 'A&M', couple: 'Aisling & Mark', maskedName: 'A. & M.',
    received: '4d ago', receivedTs: 'Fri 10 Mar 2026 · 12:14',
    weddingDate: 'Sat 18 Jul 2026', guests: 95,
    budget: { low: 90000, high: 130000 }, budgetLabel: '€90–130k',
    venueId: 'son-marroig', venueName: 'Son Marroig', venueStatus: 'Booked',
    style: 'Luxury · cliffside', priority: 'Design & atmosphere', support: 'Full-service',
    catering: 'Premium', florals: 'Statement', photo: 'Photo + video', music: 'Live band + DJ',
    extras: ['Welcome dinner'], logistics: 'Medium', complexity: 7, tier: 'Mid–Lux',
    email: 'aisling.murphy@example.com', phone: '+353 87 900 1234',
    nationality: 'Ireland', languages: 'English',
    note: "Both lawyers in Dublin. Date is set, venue is booked. Need full-service planner from this point.",
    status: 'booked', unlocked: true,
  },
];
